<a href="https://colab.research.google.com/github/mena-04/DoS-Stress-Testing/blob/main/testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!nvidia-smi
!pip uninstall -y torch torchvision torchaudio vllm
!pip install -q -U uv
!uv pip install --system vllm --torch-backend=cu130
import torch
import vllm

print("vLLM:", vllm.__version__)
print("Torch:", torch.__version__)
print("Torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

Fri Sep 11 12:22:45 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Found existing installation: torch 2.11.0+cu128
Uninstalling torch-2.11.0+cu128:
  Successfully uninstalled torch-2.11.0+cu128
Found existing installation: torchvision 0.26.0+cu128
Uninstalling torchvision-0.26.0+cu128:
  Successfully uninstalled torchvision-0.26.0+cu128
Found existing installation: torchaudio 2.11.0+cu128
Uninstalling torchaudio-2.11.0+cu128:
  Successfully uninstalled torchaudio-2.11.0+cu128
WARNING: Skipping vllm as it is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 69.9 MB/s eta 0:00:00
Using Python 3.13.15 environment at: /usr
Resolved 197 packages in 1.31s
Prepared 101 packages in 1m 06s
Uninstalled 13 packages in 153ms
Installed 101 packages in 965ms
 + agent-detector==2.0.0
 + anthropic==1.5.0
 + apache-tvm-ffi==0.1.11
 + astor==0.8.1
 + blake3==1.0.9
 + cbor2==6.1.4
 + compressed-tensors==0.17.0
 - cuda-bindings==12.9.7
 + cuda-bindings==13.4.1
 - cuda-core==0.3.2
 + cuda-core==1.2.0
 - cuda-python==12.9.7
 + cuda-python==13.4.1
 + cuda-tile==1.6.0
 - cuda-toolkit==12.8.1
 + cuda-toolkit==13.0.3.0
 + depyf==0.20.0
 + detect-installer==0.2.1
 + dnspython==2.8.0
 + email-validator==2.3.0
 - fastapi==0.141.1
 + fastapi==0.136.3
 + fastapi-cli==0.0.32
 + fastapi-cloud-cli==0.26.0
 + fastar==0.12.0
 + fastsafetensors==0.4.0
 + flashinfer-python==0.6.18
 + humming-kernels==0.1.12
 + ijson==3.5.1
 + instanttensor==0.1.9
 + interegular==0.3.3
 + jmespath==1.1.0
 - lark==1.3.1
 + lark==1.2.2
 + llguidance==1.7.6
 - llvmlite==0.44.0
 + llvmlite==0.47.0
 + lm-format-enforcer==0.11.3
 + loguru==0.7.3
 + mcp==2.2.0
 + mcp-types==2.2.0
 + mistral-common==1.11.7
 + model-hosting-container-standards==0.1.16
 + msgspec==0.21.1
 + nccl4py==0.5.0
 + ninja==1.13.2
 - numba==0.61.2
 + numba==0.65.0
 + nvidia-cublas==13.1.1.3
 + nvidia-cuda-cccl==13.3.4.2.1
 + nvidia-cuda-crt==13.4.59
 + nvidia-cuda-cupti==13.0.85
 + nvidia-cuda-nvcc==13.4.59
 + nvidia-cuda-nvdisasm==13.4.49
 + nvidia-cuda-nvrtc==13.0.88
 + nvidia-cuda-runtime==13.0.96
 + nvidia-cudnn-cu13==9.20.0.48
 + nvidia-cudnn-frontend==1.28.0
 + nvidia-cufft==12.0.0.61
 + nvidia-cufile==1.15.1.6
 + nvidia-curand==10.4.0.35
 + nvidia-cusolver==12.0.4.66
 + nvidia-cusparse==12.6.3.3
 + nvidia-cusparselt-cu13==0.8.1
 + nvidia-cutlass-dsl==4.6.2
 + nvidia-cutlass-dsl-libs-base==4.6.2
 + nvidia-cutlass-dsl-libs-core==4.6.2
 + nvidia-cutlass-dsl-libs-cu12==4.6.2
 + nvidia-cutlass-dsl-libs-cu13==4.6.2
 - nvidia-nccl-cu13==2.31.2
 + nvidia-nccl-cu13==2.29.7
 + nvidia-nvjitlink==13.4.52
 + nvidia-nvshmem-cu13==3.4.5
 + nvidia-nvtx==13.0.85
 + nvidia-nvvm==13.4.59
 - nvtx==0.2.16
 + nvtx==0.2.15
 + openai-harmony==0.0.8
 + opentelemetry-exporter-otlp==1.42.1
 + opentelemetry-exporter-otlp-proto-common==1.42.1
 + opentelemetry-exporter-otlp-proto-grpc==1.42.1
 + opentelemetry-exporter-otlp-proto-http==1.42.1
 + opentelemetry-proto==1.42.1
 + opentelemetry-semantic-conventions-ai==0.5.1
 + outlines-core==0.2.14
 + partial-json-parser==0.2.1.1.post7
 + prometheus-fastapi-instrumentator==8.1.0
 - protobuf==5.29.6
 + protobuf==6.33.6
 + pybase64==1.5.0
 + pycountry==26.2.16
 + pydantic-extra-types==2.11.1
 + pydantic-settings==2.15.0
 + pynvvideocodec==2.0.4
 + quack-kernels==0.6.4
 + rich-toolkit==0.20.5
 + rignore==0.8.1
 + setproctitle==1.3.7
 + sse-starlette==3.4.11
 + supervisor==4.3.0
 + tilelang==0.1.12
 + tokenspeed-mla==0.1.8
 + tokenspeed-triton==3.8.10.post20260906
 + torch==2.13.0+cu130
 + torch-c-dlpack-ext==0.1.5
 + torchaudio==2.11.0+cu130
 - torchcodec==0.11.0+cu128
 + torchcodec==0.16.0+cu130
 + torchvision==0.28.0+cu130
 - triton==3.6.0
 + triton==3.7.1
 + vllm==0.29.0
 + xgrammar==0.2.6
 + z3-solver==4.15.4.0

ImportError: libcudart.so.13: cannot open shared object file: No such file or directory

In [1]:
import torch
import vllm

print("vLLM:", vllm.__version__)
print("Torch:", torch.__version__)
print("Torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

vLLM: 0.29.0
Torch: 2.13.0+cu130
Torch CUDA: 13.0
CUDA available: True
GPU: Tesla T4

In [2]:
import importlib.util

print("torchaudio installed:",
      importlib.util.find_spec("torchaudio") is not None)

torchaudio installed: True

In [3]:
!pip uninstall -y torchaudio

Found existing installation: torchaudio 2.11.0+cu130
Uninstalling torchaudio-2.11.0+cu130:
  Successfully uninstalled torchaudio-2.11.0+cu130

In [4]:
import subprocess, time, requests, os, signal

# Stop old server if it exists
try:
    server.terminate()
    server.wait(timeout=10)
except:
    pass

log = open("/content/vllm.log", "w")

server = subprocess.Popen(
    [
        "vllm", "serve",
        "Qwen/Qwen2.5-0.5B-Instruct",
        "--dtype", "half",
        "--max-model-len", "2048",
        "--gpu-memory-utilization", "0.85",
        "--max-num-seqs", "8",
        "--host", "127.0.0.1",
        "--port", "8000",
    ],
    stdout=log,
    stderr=subprocess.STDOUT,
)

print("PID:", server.pid)

PID: 6832

In [5]:
for i in range(90):
    if server.poll() is not None:
        print("SERVER PROCESS EXITED")
        break

    try:
        r = requests.get(
            "http://127.0.0.1:8000/health",
            timeout=2
        )
        if r.status_code == 200:
            print("vLLM READY")
            break
    except:
        pass

    time.sleep(2)

vLLM READY

In [ ]:
!tail -n 100 /content/vllm.log

(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]        █     █     █▄   ▄█
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]  ▄▄ ▄█ █     █     █ ▀▄▀ █  version 0.29.0
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]   █▄█▀ █     █     █     █  model   Qwen/Qwen2.5-0.5B-Instruct
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]    ▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ▀     ▀
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:286] non-default args: {'model_tag': 'Qwen/Qwen2.5-0.5B-Instruct', 'host': '127.0.0.1', 'model': 'Qwen/Qwen2.5-0.5B-Instruct', 'dtype': 'half', 'max_model_len': 2048, 'gpu_memory_utilization': 0.85}
(APIServer pid=9154) Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
(APIServer pid=9154) INFO 09-11 10:53:19 [model.py:684] Resolved architecture: Qwen2ForCausalLM
(APIServer pid=9154) WARNING 09-11 10:53:19 [model.py:2355] Casting torch.bfloat16 to torch.float16.
(APIServer pid=9154) INFO 09-11 10:53:19 [model.py:2021] Using max model len 2048
(APIServer pid=9154) INFO 09-11 10:53:20 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(EngineCore pid=9336) INFO 09-11 10:53:40 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='Qwen/Qwen2.5-0.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-0.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=Qwen/Qwen2.5-0.5B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [2048], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')
(EngineCore pid=9336) INFO 09-11 10:53:44 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_6cb5f4d5ed704f729fa2ccea4e614b2a backend=nccl
(EngineCore pid=9336) INFO 09-11 10:53:44 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=9336) INFO 09-11 10:53:44 [gpu_worker.py:429] Using V2 Model Runner
(EngineCore pid=9336) INFO 09-11 10:53:46 [model_runner.py:382] Loading model from scratch...
(EngineCore pid=9336) ERROR 09-11 10:53:47 [fa_utils.py:212] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
(EngineCore pid=9336) INFO 09-11 10:53:53 [cuda.py:492] Using TRITON_ATTN attention backend out of potential backends: ['TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=9336) INFO 09-11 10:54:07 [weight_utils.py:526] Time spent downloading weights for Qwen/Qwen2.5-0.5B-Instruct: 13.148929 seconds
(EngineCore pid=9336) INFO 09-11 10:54:07 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 0.92 GiB. Available RAM: 8.67 GiB.
(EngineCore pid=9336) INFO 09-11 10:54:07 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:01<00:00,  1.04s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:01<00:00,  1.04s/it]
(EngineCore pid=9336)
(EngineCore pid=9336) INFO 09-11 10:54:08 [default_loader.py:430] Loading weights took 1.08 seconds
(EngineCore pid=9336) INFO 09-11 10:54:09 [model_runner.py:404] Model loading took 0.93 GiB memory and 24.048326 seconds
(EngineCore pid=9336) WARNING 09-11 10:54:09 [topk_topp_sampler.py:69] FlashInfer top-p/top-k sampling unavailable: unsupported compute capability 7.5; falling back. Set VLLM_USE_FLASHINFER_SAMPLER=0 to silence.
(EngineCore pid=9336) INFO 09-11 10:54:09 [utils.py:306] Using LBNHC KV cache layout.
(EngineCore pid=9336) INFO 09-11 10:54:20 [backends.py:1094] Using cache directory: /root/.cache/vllm/torch_compile_cache/013f3c2783/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=9336) INFO 09-11 10:54:20 [backends.py:1155] Dynamo bytecode transform time: 7.59 s
(EngineCore pid=9336) [rank0]:W0911 10:54:26.410000 9336 torch/_inductor/utils.py:1953] Not enough SMs to use max_autotune_gemm mode
(EngineCore pid=9336) INFO 09-11 10:54:29 [backends.py:393] Compiling a graph for compile range (1, 2048) takes 9.14 s
(EngineCore pid=9336) INFO 09-11 10:54:34 [backends.py:920] collected artifacts: 25 entries, 3 artifacts, 4806285 bytes total
(EngineCore pid=9336) INFO 09-11 10:54:34 [decorators.py:719] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/31270efa7481fb75c29d5500267756330968687c2b2ebe7da3dc9fda50a9ce26/rank_0_0/model
(EngineCore pid=9336) INFO 09-11 10:54:34 [monitor.py:53] torch.compile took 21.13 s in total
(EngineCore pid=9336) INFO 09-11 10:54:34 [monitor.py:81] Initial profiling/warmup run took 0.13 s
Capturing CUDA graphs (PIECEWISE): 100%|██████████| 51/51 [00:05<00:00,  8.86it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 23.73it/s]
(EngineCore pid=9336) INFO 09-11 10:54:43 [model_runner.py:960] Graph capturing finished in 6 secs, took 0.24 GiB
(EngineCore pid=9336) INFO 09-11 10:54:43 [gpu_worker.py:625] Available KV cache memory: 10.4 GiB
(EngineCore pid=9336) INFO 09-11 10:54:43 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.8500 is equivalent to --gpu-memory-utilization=0.8308 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.8692. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=9336) INFO 09-11 10:54:43 [kv_cache_utils.py:2032] GPU KV cache size: 908,704 tokens, Maximum concurrency for 2,048 tokens per request: 443.70x
(EngineCore pid=9336) INFO 09-11 10:54:43 [kernel_warmup.py:124] JIT kernel warmup starting.
(EngineCore pid=9336) INFO 09-11 10:54:43 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.
Capturing CUDA graphs (PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 20.34it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 35/35 [00:01<00:00, 25.33it/s]
(EngineCore pid=9336) INFO 09-11 10:54:51 [model_runner.py:960] Graph capturing finished in 5 secs, took 0.13 GiB
(EngineCore pid=9336) INFO 09-11 10:54:51 [gpu_worker.py:797] CUDA graph pool memory: 0.13 GiB (actual), 0.28 GiB (estimated), difference: 0.15 GiB (120.0%).
(EngineCore pid=9336) INFO 09-11 10:54:51 [gpu_worker.py:860] Free memory on device (14.46/14.56 GiB) on startup. Desired GPU memory utilization is (0.85, 12.38 GiB). Actual usage is 1.45 GiB for consumed memory (weights + non-torch), 0.53 GiB for peak activation, and 0.13 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=10872573645` (10.13 GiB) to fit into requested memory, or `--kv-cache-memory=13108167168` (12.21 GiB) to fully utilize gpu memory. Current kv cache memory in use is 10.4 GiB.
(EngineCore pid=9336) INFO 09-11 10:55:01 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.
(EngineCore pid=9336) INFO 09-11 10:55:02 [core.py:361] init engine (profile, create kv cache, warmup model) took 52.76 s (compilation: 21.13 s)
(EngineCore pid=9336) Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
(EngineCore pid=9336) INFO 09-11 10:55:05 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(APIServer pid=9154) INFO 09-11 10:55:05 [entry.py:135] Supported tasks: ['generate']
(APIServer pid=9154) INFO 09-11 10:55:09 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
(APIServer pid=9154) WARNING 09-11 10:55:09 [model.py:1759] Default vLLM sampling parameters have been overridden by the model's `generation_config.json`: `{'repetition_penalty': 1.1, 'temperature': 0.7, 'top_k': 20, 'top_p': 0.8}`. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
(APIServer pid=9154) INFO 09-11 10:55:09 [entry.py:139] Starting vLLM server on http://127.0.0.1:8000
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:61] Available routes are:
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /openapi.json, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /docs, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /docs/oauth2-redirect, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /redoc, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /load, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /version, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /health, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /metrics, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /tokenize, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /detokenize, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/models, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /ping, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /ping, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /invocations, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions/batch, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/responses, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/responses/{response_id}, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/responses/{response_id}/cancel, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/completions, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/messages, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/messages/count_tokens, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /generative_scoring, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /scale_elastic_ep, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /is_scaling_elastic_ep, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions/render, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/messages/render, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/completions/render, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions/derender, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/completions/derender, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /inference/v1/generate, Methods: POST
(APIServer pid=9154) INFO:     Started server process [9154]
(APIServer pid=9154) INFO:     Waiting for application startup.
(APIServer pid=9154) INFO:     Application startup complete.
(APIServer pid=9154) INFO:     127.0.0.1:55432 - "GET /health HTTP/1.1" 200 OK

In [6]:
import requests
import time

URL = "http://127.0.0.1:8000/v1/chat/completions"

payload = {
    "model": "Qwen/Qwen2.5-0.5B-Instruct",
    "messages": [
        {
            "role": "user",
            "content": "Explain AI inference in one sentence."
        }
    ],
    "max_tokens": 32,
    "temperature": 0
}

start = time.perf_counter()

r = requests.post(
    URL,
    json=payload,
    timeout=60
)

elapsed = time.perf_counter() - start

print("status:", r.status_code)
print("latency:", round(elapsed, 3), "seconds")

data = r.json()

print("response:")
print(data["choices"][0]["message"]["content"])

print("usage:")
print(data["usage"])

status: 200
latency: 0.99 seconds
response:
AI inference involves processing and analyzing large amounts of data to make predictions or decisions based on patterns and relationships within that data.
usage:
{'prompt_tokens': 37, 'total_tokens': 62, 'completion_tokens': 25, 'prompt_tokens_details': None, 'completion_tokens_details': None}

In [7]:
m = requests.get(
    "http://127.0.0.1:8000/metrics",
    timeout=10
)

print("metrics status:", m.status_code)

wanted = [
    "vllm:num_requests_running",
    "vllm:num_requests_waiting",
    "vllm:request_success_total",
    "vllm:e2e_request_latency_seconds",
    "vllm:request_queue_time_seconds",
    "vllm:prompt_tokens_total",
    "vllm:generation_tokens_total",
]

for metric in wanted:
    print("\n---", metric, "---")
    for line in m.text.splitlines():
        if line.startswith(metric):
            print(line)

metrics status: 200

--- vllm:num_requests_running ---
vllm:num_requests_running{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0

--- vllm:num_requests_waiting ---
vllm:num_requests_waiting{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:num_requests_waiting_by_reason{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct",reason="capacity"} 0.0
vllm:num_requests_waiting_by_reason{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct",reason="deferred"} 0.0

--- vllm:request_success_total ---
vllm:request_success_total{engine="0",finished_reason="stop",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_success_total{engine="0",finished_reason="length",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:request_success_total{engine="0",finished_reason="abort",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:request_success_total{engine="0",finished_reason="error",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:request_success_total{engine="0",finished_reason="repetition",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0

--- vllm:e2e_request_latency_seconds ---
vllm:e2e_request_latency_seconds_bucket{engine="0",le="0.3",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="0.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="0.8",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="1.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="1.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="2.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="2.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="5.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="10.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="15.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="20.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="30.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="40.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="50.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="60.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="120.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="240.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="480.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="960.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="1920.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="7680.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="+Inf",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_count{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_sum{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.9790487289428711
vllm:e2e_request_latency_seconds_created{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.789129729444508e+09

--- vllm:request_queue_time_seconds ---
vllm:request_queue_time_seconds_bucket{engine="0",le="0.3",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="0.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="0.8",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="1.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="1.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="2.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="2.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="5.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="10.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="15.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="20.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="30.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="40.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="50.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="60.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="120.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="240.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="480.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="960.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="1920.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="7680.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="+Inf",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_count{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_sum{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 4.018799995719746e-05
vllm:request_queue_time_seconds_created{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.7891297294445996e+09

--- vllm:prompt_tokens_total ---
vllm:prompt_tokens_total{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 37.0

--- vllm:generation_tokens_total ---
vllm:generation_tokens_total{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 25.0

# background metrics sampler

In [8]:
import threading
import requests
import time
import re
import csv

stop_sampling = False
samples = []

def get_value(text, name):
    pattern = rf'^{re.escape(name)}\{{.*?\}}\s+([0-9.eE+-]+)'
    m = re.search(pattern, text, re.MULTILINE)
    return float(m.group(1)) if m else None

def sampler():
    while not stop_sampling:
        try:
            text = requests.get(
                "http://127.0.0.1:8000/metrics",
                timeout=2
            ).text

            samples.append({
                "timestamp": time.time(),
                "running": get_value(
                    text,
                    "vllm:num_requests_running"
                ),
                "waiting": get_value(
                    text,
                    "vllm:num_requests_waiting"
                )
            })
        except Exception:
            pass

        time.sleep(0.25)

thread = threading.Thread(target=sampler, daemon=True)
thread.start()

print("sampler started")

sampler started

# concurrent overload test

In [9]:
import asyncio
import aiohttp
import time
import statistics

URL = "http://127.0.0.1:8000/v1/chat/completions"
MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30

async def send_one(session, i):
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "user", "content": EXPENSIVE_PROMPT}
        ],
        "max_tokens": 256,
        "temperature": 0
    }

    start = time.perf_counter()

    try:
        async with session.post(URL, json=payload, timeout=120) as r:
            await r.text()
            latency = time.perf_counter() - start
            return {
                "id": i,
                "status": r.status,
                "latency": latency
            }
    except Exception as e:
        return {
            "id": i,
            "status": "error",
            "latency": time.perf_counter() - start
        }



async def run_load(n=50):
    async with aiohttp.ClientSession() as session:
        tasks = [
            asyncio.create_task(send_one(session, i))
            for i in range(n)
        ]
        return await asyncio.gather(*tasks)

results = await run_load(40)

latencies = [
    r["latency"]
    for r in results
    if r["status"] == 200
]

print("completed:", len(results))
print("successful:", len(latencies))

if latencies:
    print("p50:", round(statistics.median(latencies), 3))

    sorted_lat = sorted(latencies)
    p95_index = int(0.95 * len(sorted_lat)) - 1
    print("p95:", round(sorted_lat[p95_index], 3))

    print("max:", round(max(latencies), 3))

completed: 40
successful: 40
p50: 7.677
p95: 12.177
max: 12.178

In [10]:
stop_sampling = True
thread.join(timeout=2)

print("samples:", len(samples))
print("max running:", max(x["running"] or 0 for x in samples))
print("max waiting:", max(x["waiting"] or 0 for x in samples))

samples: 148
max running: 8.0
max waiting: 32.0

# Load generator

In [11]:
!pip install -q locust
!locust --version

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 63.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 69.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.4/115.4 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.3/60.3 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.6/270.6 kB 25.3 MB/s eta 0:00:00
locust 2.46.5 from /usr/local/lib/python3.13/dist-packages/locust (Python 3.13.15)

In [12]:
%%writefile /content/locustfile.py
# first testing with normal traffic
from locust import HttpUser, task, between
import random


MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 4

    @task
    def legitimate_request(self):
        payload = {
            "model": MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": SMALL_PROMPT
                }
            ],
            "max_tokens": 32,
            "temperature": 0
        }

        self.client.post(
            "/v1/chat/completions",
            json=payload,
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(0.05, 0.15)
    weight = 1

    @task
    def attack_request(self):
        payload = {
            "model": MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": EXPENSIVE_PROMPT
                }
            ],
            "max_tokens": 256,
            "temperature": 0
        }

        self.client.post(
            "/v1/chat/completions",
            json=payload,
            name="attacker"
        )

Writing /content/locustfile.py

In [13]:
!mkdir -p /content/results

In [16]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --users 4 \
  --spawn-rate 2 \
  --run-time 15s \
  --csv /content/results/normal \
  --csv-full-history \
  LegitimateUser

[2026-09-11 12:38:48,166] 9d728fde6ca4/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 12:38:48,167] 9d728fde6ca4/INFO/locust.main: Run time limit set to 15 seconds
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 12:38:48,168] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 2.00 per second
[2026-09-11 12:38:49,170] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       7     0(0.00%) |    220     206     252    210 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       7     0(0.00%) |    220     206     252    210 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      14     0(0.00%) |    212     201     252    210 |    3.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      14     0(0.00%) |    212     201     252    210 |    3.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      22     0(0.00%) |    211     201     252    210 |    3.25        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      22     0(0.00%) |    211     201     252    210 |    3.25        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      29     0(0.00%) |    212     201     252    210 |    3.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      29     0(0.00%) |    212     201     252    210 |    3.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      36     0(0.00%) |    212     201     252    210 |    3.62        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      36     0(0.00%) |    212     201     252    210 |    3.62        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      42     0(0.00%) |    211     201     252    210 |    3.67        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      42     0(0.00%) |    211     201     252    210 |    3.67        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      48     0(0.00%) |    213     201     335    210 |    3.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      48     0(0.00%) |    213     201     335    210 |    3.60        0.00

[2026-09-11 12:39:02,927] 9d728fde6ca4/INFO/locust.main: --run-time limit reached, shutting down
[2026-09-11 12:39:03,022] 9d728fde6ca4/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      50     0(0.00%) |    217     201     335    210 |    3.54        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      50     0(0.00%) |    217     201     335    210 |    3.54        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     legitimate      210    210    220    220    250    310    340    340    340    340    340     50
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated      210    210    220    220    250    310    340    340    340    340    340     50

In [17]:
import pandas as pd

df = pd.read_csv("/content/results/normal_stats.csv")
display(df)

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,legitimate,48,0,210,213.737979,201.095848,335.048178,870.0,3.452947,...,210,210,220,220,250,340,340,340,340,340
1,NaN,Aggregated,48,0,210,213.737979,201.095848,335.048178,870.0,3.452947,...,210,210,220,220,250,340,340,340,340,340

In [18]:
%%writefile /content/locustfile.py
# sudden spike
from locust import HttpUser, task, between, LoadTestShape

MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 1

    @task
    def legitimate_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": SMALL_PROMPT
                    }
                ],
                "max_tokens": 32,
                "temperature": 0
            },
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(0.05, 0.15)
    weight = 1

    @task
    def attack_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": MEDIUM_PROMPT
                    }
                ],
                "max_tokens": 128,
                "temperature": 0
            },
            name="attacker"
        )


class SpikeShape(LoadTestShape):

    def tick(self):
        run_time = self.get_run_time()

        # 0-10s: legitimate traffic only
        if run_time < 10:
            return (
                4,
                4,
                [LegitimateUser]
            )

        # 10-20s: sudden attacker spike
        if run_time < 20:
            return (
                24,
                20,
                [LegitimateUser, AttackerUser]
            )

        # 20-30s: attack stops, return to normal
        if run_time < 30:
            return (
                4,
                20,
                [LegitimateUser]
            )

        return None

Overwriting /content/locustfile.py

In [19]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --csv /content/results/spike \
  --csv-full-history

[2026-09-11 12:43:51,330] 9d728fde6ca4/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 12:43:51,330] 9d728fde6ca4/INFO/locust.runners: Shape test starting.
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 12:43:51,331] 9d728fde6ca4/INFO/locust.runners: Shape worker starting
[2026-09-11 12:43:51,332] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 12:43:51,332] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 12:43:51,332] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       8     0(0.00%) |    244     198     285    220 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       8     0(0.00%) |    244     198     285    220 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      16     0(0.00%) |    225     198     285    210 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      16     0(0.00%) |    225     198     285    210 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      20     0(0.00%) |    223     198     285    210 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      20     0(0.00%) |    223     198     285    210 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      27     0(0.00%) |    238     198     426    210 |    3.33        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      27     0(0.00%) |    238     198     426    210 |    3.33        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      31     0(0.00%) |    236     198     426    210 |    3.14        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      31     0(0.00%) |    236     198     426    210 |    3.14        0.00

[2026-09-11 12:44:01,345] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 24 users at 20.00 spawn rate
[2026-09-11 12:44:01,346] 9d728fde6ca4/INFO/locust.runners: Ramping to 24 users at a rate of 20.00 per second
[2026-09-11 12:44:01,349] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 10, "LegitimateUser": 14} (24 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      10     0(0.00%) |   1217     992    1945   1000 |    0.00        0.00
POST     legitimate      46     0(0.00%) |    536     198    1592    230 |    3.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      56     0(0.00%) |    658     198    1945    280 |    3.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      24     0(0.00%) |   1340     992    1945   1300 |    0.80        0.00
POST     legitimate      58     0(0.00%) |    586     198    1592    280 |    3.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      82     0(0.00%) |    806     198    1945    790 |    4.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      36     0(0.00%) |   1370     992    1945   1300 |    2.00        0.00
POST     legitimate      75     0(0.00%) |    637     198    1592    570 |    4.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     111     0(0.00%) |    874     198    1945    910 |    6.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      49     0(0.00%) |   1388     992    1945   1300 |    3.40        0.00
POST     legitimate      89     0(0.00%) |    663     198    1592    690 |    5.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     138     0(0.00%) |    921     198    1945    920 |    8.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    4.60        0.00
POST     legitimate     105     0(0.00%) |    675     198    1592    710 |    6.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     167     0(0.00%) |    947     198    1945    930 |   10.90        0.00

[2026-09-11 12:44:11,364] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 4 users at 20.00 spawn rate
[2026-09-11 12:44:11,365] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 20.00 per second
[2026-09-11 12:44:11,379] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    6.00        0.00
POST     legitimate     111     0(0.00%) |    662     198    1592    690 |    7.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     173     0(0.00%) |    929     198    1945    910 |   13.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    6.20        0.00
POST     legitimate     117     0(0.00%) |    648     198    1592    650 |    7.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     179     0(0.00%) |    910     198    1945    880 |   13.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    4.20        0.00
POST     legitimate     123     0(0.00%) |    630     198    1592    630 |    6.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     185     0(0.00%) |    890     198    1945    850 |   10.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    3.60        0.00
POST     legitimate     129     0(0.00%) |    611     198    1592    610 |    5.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     191     0(0.00%) |    869     198    1945    840 |    8.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    1.60        0.00
POST     legitimate     137     0(0.00%) |    587     198    1592    570 |    4.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     199     0(0.00%) |    843     198    1945    830 |    5.80        0.00

[2026-09-11 12:44:21,393] 9d728fde6ca4/INFO/locust.runners: Shape test stopping
[2026-09-11 12:44:21,412] 9d728fde6ca4/INFO/locust.main: Shape test completed, shutting down
[2026-09-11 12:44:21,412] 9d728fde6ca4/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1407     992    1945   1400 |    2.07        0.00
POST     legitimate     137     0(0.00%) |    587     198    1592    570 |    4.57        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     199     0(0.00%) |    843     198    1945    830 |    6.65        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     attacker     1400   1500   1500   1600   1600   1700   1900   1900   1900   1900   1900     62
POST     legitimate      570    750    830    880   1000   1400   1500   1500   1600   1600   1600    137
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated      830   1100   1300   1400   1500   1600   1700   1900   1900   1900   1900    199

In [20]:
import pandas as pd

df = pd.read_csv("/content/results/spike_stats.csv")
display(df)

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,attacker,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677,2.070404,...,1500,1500,1600,1600,1700,1900,1900,1900,1900,1900
1,POST,legitimate,137,0,570,587.842140,198.191600,1592.788929,870.000000,4.574925,...,750,830,880,1000,1400,1500,1500,1600,1600,1600
2,NaN,Aggregated,199,0,830,843.114706,198.191600,1945.796912,1039.396985,6.645330,...,1100,1300,1400,1500,1600,1700,1900,1900,1900,1900

In [21]:
hist = pd.read_csv("/content/results/spike_stats_history.csv")

display(hist.tail(20))

,Timestamp,User Count,Type,Name,Requests/s,Failures/s,50%,66%,75%,80%,...,99.9%,99.99%,100%,Total Request Count,Total Failure Count,Total Median Response Time,Total Average Response Time,Total Min Response Time,Total Max Response Time,Total Average Content Size
60,1789130655,4,POST,legitimate,7.5,0.0,750.0,830.0,860.0,900.0,...,1100.0,1100.0,1100.0,117,0,650,648.004295,198.191600,1592.788929,870.000000
61,1789130655,4,NaN,Aggregated,13.7,0.0,930.0,1300.0,1400.0,1500.0,...,1800.0,1800.0,1800.0,179,0,880,910.960647,198.191600,1945.796912,1058.324022
62,1789130656,4,POST,attacker,4.7,0.0,1500.0,1500.0,1500.0,1600.0,...,1700.0,1700.0,1700.0,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677
63,1789130656,4,POST,legitimate,6.7,0.0,710.0,760.0,830.0,850.0,...,1000.0,1000.0,1000.0,121,0,630,636.863708,198.191600,1592.788929,870.000000
64,1789130656,4,NaN,Aggregated,11.4,0.0,850.0,1300.0,1400.0,1500.0,...,1700.0,1700.0,1700.0,183,0,850,897.846787,198.191600,1945.796912,1054.207650
65,1789130657,4,POST,attacker,4.2,0.0,1500.0,1500.0,1500.0,1600.0,...,1600.0,1600.0,1600.0,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677
66,1789130657,4,POST,legitimate,6.1,0.0,650.0,760.0,780.0,850.0,...,1000.0,1000.0,1000.0,123,0,630,630.038595,198.191600,1592.788929,870.000000
67,1789130657,4,NaN,Aggregated,10.3,0.0,780.0,930.0,1400.0,1400.0,...,1600.0,1600.0,1600.0,185,0,850,890.487570,198.191600,1945.796912,1052.216216
68,1789130658,4,POST,attacker,4.2,0.0,1500.0,1500.0,1500.0,1500.0,...,1600.0,1600.0,1600.0,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677
69,1789130658,4,POST,legitimate,6.1,0.0,570.0,690.0,760.0,760.0,...,930.0,930.0,930.0,125,0,620,624.403010,198.191600,1592.788929,870.000000
70,1789130658,4,NaN,Aggregated,10.3,0.0,750.0,920.0,1400.0,1400.0,...,1600.0,1600.0,1600.0,187,0,850,883.934917,198.191600,1945.796912,1050.267380
71,1789130659,4,POST,attacker,3.6,0.0,1500.0,1500.0,1500.0,1500.0,...,1600.0,1600.0,1600.0,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677
72,1789130659,4,POST,legitimate,5.3,0.0,330.0,510.0,610.0,760.0,...,930.0,930.0,930.0,129,0,610,611.420087,198.191600,1592.788929,870.000000
73,1789130659,4,NaN,Aggregated,8.9,0.0,500.0,760.0,880.0,930.0,...,1600.0,1600.0,1600.0,191,0,840,869.731123,198.191600,1945.796912,1046.492147
74,1789130660,4,POST,attacker,2.1,0.0,1600.0,1600.0,1600.0,1600.0,...,1600.0,1600.0,1600.0,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677
75,1789130660,4,POST,legitimate,4.7,0.0,300.0,320.0,410.0,500.0,...,760.0,760.0,760.0,133,0,580,599.264982,198.191600,1592.788929,870.000000
76,1789130660,4,NaN,Aggregated,6.8,0.0,300.0,340.0,500.0,510.0,...,1600.0,1600.0,1600.0,195,0,830,856.142030,198.191600,1945.796912,1042.871795
77,1789130661,4,POST,attacker,1.6,0.0,1600.0,1600.0,1600.0,1600.0,...,1600.0,1600.0,1600.0,62,0,1400,1407.184731,992.891218,1945.796912,1413.709677
78,1789130661,4,POST,legitimate,4.2,0.0,220.0,310.0,320.0,340.0,...,570.0,570.0,570.0,137,0,570,587.842140,198.191600,1592.788929,870.000000
79,1789130661,4,NaN,Aggregated,5.8,0.0,220.0,310.0,320.0,340.0,...,570.0,570.0,570.0,199,0,830,843.114706,198.191600,1945.796912,1039.396985

In [22]:
%%writefile /content/locustfile.py
# sustained flood
from locust import HttpUser, task, between, LoadTestShape

MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 1

    @task
    def legitimate_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": SMALL_PROMPT
                    }
                ],
                "max_tokens": 32,
                "temperature": 0
            },
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(0.05, 0.15)
    weight = 1

    @task
    def attack_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": MEDIUM_PROMPT
                    }
                ],
                "max_tokens": 128,
                "temperature": 0
            },
            name="attacker"
        )


class FloodShape(LoadTestShape):

    def tick(self):
        run_time = self.get_run_time()

        # 0-10s: normal legitimate traffic
        if run_time < 10:
            return (
                4,
                4,
                [LegitimateUser]
            )

        # 10-40s: sustained flood
        if run_time < 40:
            return (
                32,
                20,
                [LegitimateUser, AttackerUser]
            )

        # 40-50s: recovery
        if run_time < 50:
            return (
                4,
                20,
                [LegitimateUser]
            )

        return None

Overwriting /content/locustfile.py

In [23]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --csv /content/results/flood \
  --csv-full-history

[2026-09-11 12:49:31,789] 9d728fde6ca4/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 12:49:31,790] 9d728fde6ca4/INFO/locust.runners: Shape test starting.
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 12:49:31,791] 9d728fde6ca4/INFO/locust.runners: Shape worker starting
[2026-09-11 12:49:31,791] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 12:49:31,791] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 12:49:31,792] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       9     0(0.00%) |    236     199     277    220 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       9     0(0.00%) |    236     199     277    220 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      17     0(0.00%) |    222     199     277    210 |    2.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      17     0(0.00%) |    222     199     277    210 |    2.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      23     0(0.00%) |    218     197     277    210 |    3.25        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      23     0(0.00%) |    218     197     277    210 |    3.25        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      29     0(0.00%) |    216     197     277    210 |    3.33        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      29     0(0.00%) |    216     197     277    210 |    3.33        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      37     0(0.00%) |    222     197     291    210 |    3.38        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      37     0(0.00%) |    222     197     291    210 |    3.38        0.00

[2026-09-11 12:49:41,803] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 32 users at 20.00 spawn rate
[2026-09-11 12:49:41,803] 9d728fde6ca4/INFO/locust.runners: Ramping to 32 users at a rate of 20.00 per second
[2026-09-11 12:49:42,809] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 14, "LegitimateUser": 18} (32 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      10     0(0.00%) |   1199     976    1964    980 |    0.00        0.00
POST     legitimate      53     0(0.00%) |    498     197    1493    220 |    3.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      63     0(0.00%) |    610     197    1964    260 |    3.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      18     0(0.00%) |   1491     976    2184   1400 |    0.70        0.00
POST     legitimate      58     0(0.00%) |    588     197    2177    230 |    3.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      76     0(0.00%) |    802     197    2184    290 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      30     0(0.00%) |   2009     976    3210   2100 |    1.60        0.00
POST     legitimate      73     0(0.00%) |    866     197    2186    290 |    4.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     103     0(0.00%) |   1199     197    3210   1100 |    5.80        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      42     0(0.00%) |   2023     976    3210   2000 |    2.40        0.00
POST     legitimate      91     0(0.00%) |    969     197    2186   1200 |    5.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     133     0(0.00%) |   1302     197    3210   1400 |    7.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      56     0(0.00%) |   2032     976    3210   2000 |    4.00        0.00
POST     legitimate     107     0(0.00%) |   1017     197    2186   1200 |    5.90        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     163     0(0.00%) |   1366     197    3210   1400 |    9.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      70     0(0.00%) |   2034     976    3210   2000 |    5.20        0.00
POST     legitimate     121     0(0.00%) |   1054     197    2186   1200 |    6.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     191     0(0.00%) |   1413     197    3210   1400 |   11.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      84     0(0.00%) |   2036     976    3210   2000 |    5.80        0.00
POST     legitimate     138     0(0.00%) |   1104     197    2186   1300 |    7.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     222     0(0.00%) |   1457     197    3210   1500 |   13.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      97     0(0.00%) |   2056     976    3210   2100 |    6.10        0.00
POST     legitimate     150     0(0.00%) |   1139     197    2186   1300 |    7.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     247     0(0.00%) |   1499     197    3210   1500 |   13.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     105     0(0.00%) |   2070     976    3210   2100 |    6.70        0.00
POST     legitimate     166     0(0.00%) |   1185     197    2186   1400 |    7.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     271     0(0.00%) |   1528     197    3210   1600 |   14.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     120     0(0.00%) |   2072     976    3210   2100 |    6.40        0.00
POST     legitimate     183     0(0.00%) |   1208     197    2186   1400 |    7.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     303     0(0.00%) |   1550     197    3210   1600 |   14.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     133     0(0.00%) |   2069     976    3210   2100 |    6.20        0.00
POST     legitimate     199     0(0.00%) |   1219     197    2186   1400 |    7.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     332     0(0.00%) |   1560     197    3210   1600 |   13.80        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     147     0(0.00%) |   2066     976    3210   2100 |    6.40        0.00
POST     legitimate     215     0(0.00%) |   1229     197    2186   1400 |    7.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     362     0(0.00%) |   1569     197    3210   1600 |   14.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     160     0(0.00%) |   2065     976    3210   2100 |    6.50        0.00
POST     legitimate     231     0(0.00%) |   1239     197    2186   1400 |    7.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     391     0(0.00%) |   1577     197    3210   1600 |   14.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     172     0(0.00%) |   2065     976    3210   2100 |    6.40        0.00
POST     legitimate     244     0(0.00%) |   1244     197    2186   1400 |    7.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     416     0(0.00%) |   1583     197    3210   1600 |   14.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     184     0(0.00%) |   2074     976    3210   2100 |    6.40        0.00
POST     legitimate     259     0(0.00%) |   1258     197    2186   1400 |    7.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     443     0(0.00%) |   1597     197    3210   1600 |   14.00        0.00

[2026-09-11 12:50:11,864] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 4 users at 20.00 spawn rate
[2026-09-11 12:50:11,865] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 20.00 per second
[2026-09-11 12:50:12,868] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     189     0(0.00%) |   2066     955    3210   2100 |    6.60        0.00
POST     legitimate     270     0(0.00%) |   1233     197    2186   1400 |    7.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     459     0(0.00%) |   1576     197    3210   1600 |   14.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     189     0(0.00%) |   2066     955    3210   2100 |    6.00        0.00
POST     legitimate     278     0(0.00%) |   1203     197    2186   1400 |    7.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     467     0(0.00%) |   1553     197    3210   1500 |   13.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     189     0(0.00%) |   2066     955    3210   2100 |    4.70        0.00
POST     legitimate     285     0(0.00%) |   1179     196    2186   1300 |    6.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     474     0(0.00%) |   1533     196    3210   1500 |   11.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     189     0(0.00%) |   2066     955    3210   2100 |    3.40        0.00
POST     legitimate     293     0(0.00%) |   1152     196    2186   1300 |    5.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     482     0(0.00%) |   1510     196    3210   1500 |    9.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     189     0(0.00%) |   2066     955    3210   2100 |    2.10        0.00
POST     legitimate     298     0(0.00%) |   1136     196    2186   1300 |    5.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     487     0(0.00%) |   1497     196    3210   1500 |    7.10        0.00

[2026-09-11 12:50:21,876] 9d728fde6ca4/INFO/locust.runners: Shape test stopping
[2026-09-11 12:50:21,945] 9d728fde6ca4/INFO/locust.main: Shape test completed, shutting down
[2026-09-11 12:50:21,946] 9d728fde6ca4/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     189     0(0.00%) |   2066     955    3210   2100 |    3.77        0.00
POST     legitimate     299     0(0.00%) |   1133     196    2186   1300 |    5.96        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     488     0(0.00%) |   1494     196    3210   1500 |    9.73        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     attacker     2100   2100   2200   2200   2300   2600   3000   3100   3200   3200   3200    189
POST     legitimate     1300   1400   1500   1500   1700   1800   2000   2000   2200   2200   2200    299
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated     1500   2000   2000   2100   2200   2300   2600   2800   3200   3200   3200    488

In [24]:
import pandas as pd

df = pd.read_csv("/content/results/flood_stats.csv")
display(df)

hist = pd.read_csv("/content/results/flood_stats_history.csv")
display(hist.tail(30))

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,attacker,189,0,2100,2066.455697,955.254715,3210.393183,1414.00000,3.801247,...,2100,2200,2200,2300,2600,3000,3100,3200,3200,3200
1,POST,legitimate,298,0,1300,1136.721806,196.579744,2186.271675,870.00000,5.993500,...,1400,1500,1500,1700,1800,2000,2000,2200,2200,2200
2,NaN,Aggregated,487,0,1500,1497.542557,196.579744,3210.393183,1081.12115,9.794747,...,2000,2000,2100,2200,2300,2600,2800,3200,3200,3200

,Timestamp,User Count,Type,Name,Requests/s,Failures/s,50%,66%,75%,80%,...,99.9%,99.99%,100%,Total Request Count,Total Failure Count,Total Median Response Time,Total Average Response Time,Total Min Response Time,Total Max Response Time,Total Average Content Size
111,1789131012,12,POST,attacker,6.4,0.0,2100.0,2100.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
112,1789131012,12,POST,legitimate,8.0,0.0,1400.0,1400.0,1400.0,1500.0,...,1600.0,1600.0,1600.0,268,0,1400,1241.211519,197.265116,2186.271675,870.000000
113,1789131012,12,NaN,Aggregated,14.4,0.0,1500.0,2000.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,457,0,1600,1582.505063,197.265116,3210.393183,1094.980306
114,1789131013,4,POST,attacker,6.6,0.0,2100.0,2100.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
115,1789131013,4,POST,legitimate,7.7,0.0,1400.0,1400.0,1500.0,1500.0,...,1600.0,1600.0,1600.0,270,0,1400,1233.530908,197.265116,2186.271675,870.000000
116,1789131013,4,NaN,Aggregated,14.3,0.0,1500.0,2000.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,459,0,1600,1576.499939,197.265116,3210.393183,1094.000000
117,1789131014,4,POST,attacker,6.2,0.0,2100.0,2100.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
118,1789131014,4,POST,legitimate,7.6,0.0,1400.0,1400.0,1400.0,1500.0,...,1600.0,1600.0,1600.0,274,0,1400,1218.573281,197.265116,2186.271675,870.000000
119,1789131014,4,NaN,Aggregated,13.8,0.0,1500.0,2000.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,463,0,1500,1564.685109,197.265116,3210.393183,1092.064795
120,1789131015,4,POST,attacker,6.0,0.0,2100.0,2100.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
121,1789131015,4,POST,legitimate,7.5,0.0,1400.0,1400.0,1400.0,1500.0,...,1600.0,1600.0,1600.0,278,0,1400,1203.992442,197.265116,2186.271675,870.000000
122,1789131015,4,NaN,Aggregated,13.5,0.0,1500.0,2000.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,467,0,1500,1553.040740,197.265116,3210.393183,1090.162741
123,1789131016,4,POST,attacker,5.5,0.0,2100.0,2200.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
124,1789131016,4,POST,legitimate,7.0,0.0,1300.0,1400.0,1400.0,1500.0,...,1600.0,1600.0,1600.0,281,0,1400,1193.283256,197.265116,2186.271675,870.000000
125,1789131016,4,NaN,Aggregated,12.5,0.0,1500.0,2000.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,470,0,1500,1544.410046,197.265116,3210.393183,1088.757447
126,1789131017,4,POST,attacker,4.7,0.0,2100.0,2200.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
127,1789131017,4,POST,legitimate,6.6,0.0,1300.0,1400.0,1400.0,1500.0,...,1600.0,1600.0,1600.0,285,0,1300,1179.335967,196.579744,2186.271675,870.000000
128,1789131017,4,NaN,Aggregated,11.3,0.0,1400.0,1600.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,474,0,1500,1533.060923,196.579744,3210.393183,1086.911392
129,1789131018,4,POST,attacker,4.1,0.0,2200.0,2200.0,2200.0,2200.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
130,1789131018,4,POST,legitimate,6.2,0.0,680.0,1400.0,1400.0,1500.0,...,1600.0,1600.0,1600.0,289,0,1300,1165.792917,196.579744,2186.271675,870.000000
131,1789131018,4,NaN,Aggregated,10.3,0.0,1400.0,1500.0,2100.0,2100.0,...,2400.0,2400.0,2400.0,478,0,1500,1521.912719,196.579744,3210.393183,1085.096234
132,1789131019,4,POST,attacker,3.4,0.0,2200.0,2200.0,2300.0,2300.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
133,1789131019,4,POST,legitimate,5.8,0.0,220.0,860.0,1400.0,1400.0,...,1600.0,1600.0,1600.0,293,0,1300,1152.685842,196.579744,2186.271675,870.000000
134,1789131019,4,NaN,Aggregated,9.2,0.0,860.0,1500.0,1500.0,2100.0,...,2400.0,2400.0,2400.0,482,0,1500,1510.989789,196.579744,3210.393183,1083.311203
135,1789131020,4,POST,attacker,2.8,0.0,2200.0,2200.0,2300.0,2400.0,...,2400.0,2400.0,2400.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
136,1789131020,4,POST,legitimate,5.3,0.0,210.0,220.0,680.0,1300.0,...,1600.0,1600.0,1600.0,295,0,1300,1146.238317,196.579744,2186.271675,870.000000
137,1789131020,4,NaN,Aggregated,8.1,0.0,220.0,960.0,1400.0,1500.0,...,2400.0,2400.0,2400.0,484,0,1500,1505.579401,196.579744,3210.393183,1082.429752
138,1789131021,4,POST,attacker,2.1,0.0,1400.0,1400.0,2100.0,2100.0,...,2100.0,2100.0,2100.0,189,0,2100,2066.455697,955.254715,3210.393183,1414.000000
139,1789131021,4,POST,legitimate,5.0,0.0,200.0,210.0,220.0,220.0,...,1300.0,1300.0,1300.0,298,0,1300,1136.721806,196.579744,2186.271675,870.000000
140,1789131021,4,NaN,Aggregated,7.1,0.0,200.0,210.0,220.0,220.0,...,2100.0,2100.0,2100.0,487,0,1500,1497.542557,196.579744,3210.393183,1081.121150

In [26]:
%%writefile /content/locustfile.py
# low-and-slow
from locust import HttpUser, task, between, LoadTestShape

MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 1

    @task
    def legitimate_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": SMALL_PROMPT
                    }
                ],
                "max_tokens": 32,
                "temperature": 0
            },
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(1.5, 2.5)

    @task
    def attack_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": EXPENSIVE_PROMPT
                    }
                ],
                "max_tokens": 256,
                "temperature": 0
            },
            name="attacker"
        )


class LowSlowShape(LoadTestShape):

    def tick(self):
        run_time = self.get_run_time()

        # 0-10s: normal traffic only
        if run_time < 10:
            return (
                4,
                4,
                [LegitimateUser]
            )

        # 10-40s: low-rate expensive attackers appear
        if run_time < 40:
            return (
                8,
                2,
                [LegitimateUser, AttackerUser]
            )

        # 40-50s: attacker disappears
        if run_time < 50:
            return (
                4,
                4,
                [LegitimateUser]
            )

        return None

Overwriting /content/locustfile.py

In [27]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --csv /content/results/low_slow \
  --csv-full-history

[2026-09-11 13:02:07,486] 9d728fde6ca4/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 13:02:07,487] 9d728fde6ca4/INFO/locust.runners: Shape test starting.
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 13:02:07,488] 9d728fde6ca4/INFO/locust.runners: Shape worker starting
[2026-09-11 13:02:07,488] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 13:02:07,489] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 13:02:07,489] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       8     0(0.00%) |    239     199     283    200 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       8     0(0.00%) |    239     199     283    200 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      16     0(0.00%) |    221     199     283    200 |    3.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      16     0(0.00%) |    221     199     283    200 |    3.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      24     0(0.00%) |    216     199     283    200 |    3.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      24     0(0.00%) |    216     199     283    200 |    3.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      30     0(0.00%) |    214     199     283    200 |    3.33        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      30     0(0.00%) |    214     199     283    200 |    3.33        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      35     0(0.00%) |    218     196     328    200 |    3.57        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      35     0(0.00%) |    218     196     328    200 |    3.57        0.00

[2026-09-11 13:02:17,501] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 8 users at 2.00 spawn rate
[2026-09-11 13:02:17,501] 9d728fde6ca4/INFO/locust.runners: Ramping to 8 users at a rate of 2.00 per second
[2026-09-11 13:02:18,511] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 2, "LegitimateUser": 6} (8 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      40     0(0.00%) |    283     196    1146    210 |    3.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      40     0(0.00%) |    283     196    1146    210 |    3.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       2     0(0.00%) |   3025    2676    3374   2700 |    0.00        0.00
POST     legitimate      51     0(0.00%) |    327     196    1146    210 |    3.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      53     0(0.00%) |    429     196    3374    220 |    3.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       2     0(0.00%) |   3025    2676    3374   2700 |    0.10        0.00
POST     legitimate      60     0(0.00%) |    310     196    1146    210 |    3.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      62     0(0.00%) |    397     196    3374    210 |    3.60        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       4     0(0.00%) |   2395    1766    3374   1800 |    0.20        0.00
POST     legitimate      69     0(0.00%) |    299     196    1146    210 |    3.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      73     0(0.00%) |    414     196    3374    220 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       4     0(0.00%) |   2395    1766    3374   1800 |    0.40        0.00
POST     legitimate      78     0(0.00%) |    290     196    1146    210 |    3.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      82     0(0.00%) |    392     196    3374    220 |    4.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       6     0(0.00%) |   2184    1761    3374   1800 |    0.40        0.00
POST     legitimate      87     0(0.00%) |    284     196    1146    220 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      93     0(0.00%) |    406     196    3374    220 |    4.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       6     0(0.00%) |   2184    1761    3374   1800 |    0.50        0.00
POST     legitimate      98     0(0.00%) |    278     196    1146    220 |    4.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     104     0(0.00%) |    388     196    3374    220 |    5.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       8     0(0.00%) |   2102    1761    3374   1800 |    0.60        0.00
POST     legitimate     105     0(0.00%) |    276     196    1146    220 |    4.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     113     0(0.00%) |    405     196    3374    230 |    5.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       8     0(0.00%) |   2102    1761    3374   1800 |    0.60        0.00
POST     legitimate     115     0(0.00%) |    271     196    1146    220 |    4.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     123     0(0.00%) |    390     196    3374    230 |    5.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      10     0(0.00%) |   2037    1761    3374   1800 |    0.40        0.00
POST     legitimate     125     0(0.00%) |    267     196    1146    220 |    4.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     135     0(0.00%) |    399     196    3374    230 |    5.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      10     0(0.00%) |   2037    1761    3374   1800 |    0.60        0.00
POST     legitimate     135     0(0.00%) |    264     196    1146    220 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     145     0(0.00%) |    386     196    3374    230 |    5.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      12     0(0.00%) |   1994    1761    3374   1800 |    0.50        0.00
POST     legitimate     143     0(0.00%) |    262     196    1146    220 |    4.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     155     0(0.00%) |    396     196    3374    230 |    5.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      12     0(0.00%) |   1994    1761    3374   1800 |    0.40        0.00
POST     legitimate     153     0(0.00%) |    259     196    1146    220 |    4.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     165     0(0.00%) |    385     196    3374    230 |    5.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.40        0.00
POST     legitimate     163     0(0.00%) |    259     196    1146    220 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     177     0(0.00%) |    394     196    3374    230 |    5.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.60        0.00
POST     legitimate     172     0(0.00%) |    257     196    1146    220 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     186     0(0.00%) |    386     196    3374    230 |    5.40        0.00

[2026-09-11 13:02:47,554] 9d728fde6ca4/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 13:02:47,554] 9d728fde6ca4/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 13:02:47,556] 9d728fde6ca4/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.60        0.00
POST     legitimate     178     0(0.00%) |    255     196    1146    220 |    4.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     192     0(0.00%) |    380     196    3374    230 |    5.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.40        0.00
POST     legitimate     187     0(0.00%) |    253     196    1146    220 |    4.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     201     0(0.00%) |    372     196    3374    220 |    5.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.40        0.00
POST     legitimate     192     0(0.00%) |    252     196    1146    220 |    4.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     206     0(0.00%) |    368     196    3374    220 |    4.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.20        0.00
POST     legitimate     202     0(0.00%) |    249     196    1146    210 |    3.90        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     216     0(0.00%) |    361     196    3374    220 |    4.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.00        0.00
POST     legitimate     208     0(0.00%) |    248     196    1146    210 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     222     0(0.00%) |    357     196    3374    220 |    4.00        0.00

[2026-09-11 13:02:57,568] 9d728fde6ca4/INFO/locust.runners: Shape test stopping
[2026-09-11 13:02:57,586] 9d728fde6ca4/INFO/locust.main: Shape test completed, shutting down
[2026-09-11 13:02:57,586] 9d728fde6ca4/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1967    1761    3374   1800 |    0.28        0.00
POST     legitimate     208     0(0.00%) |    248     196    1146    210 |    4.16        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     222     0(0.00%) |    357     196    3374    220 |    4.44        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     attacker     1800   1800   1800   1900   2700   3400   3400   3400   3400   3400   3400     14
POST     legitimate      210    230    240    250    270    330    710   1000   1100   1100   1100    208
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated      220    240    250    250    490   1800   1800   1900   3400   3400   3400    222

In [28]:
import pandas as pd

df = pd.read_csv("/content/results/low_slow_stats.csv")
display(df)

hist = pd.read_csv("/content/results/low_slow_stats_history.csv")
display(hist.tail(30))

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,attacker,14,0,1800,1967.481917,1761.399410,3374.858091,2114.00000,0.279836,...,1800,1800,1900,2700,3400,3400,3400,3400,3400,3400
1,POST,legitimate,208,0,210,248.690992,196.388284,1146.079165,870.00000,4.157562,...,230,240,250,270,330,710,1000,1100,1100,1100
2,NaN,Aggregated,222,0,220,357.083212,196.388284,3374.858091,948.45045,4.437398,...,240,250,250,490,1800,1800,1900,3400,3400,3400

,Timestamp,User Count,Type,Name,Requests/s,Failures/s,50%,66%,75%,80%,...,99.9%,99.99%,100%,Total Request Count,Total Failure Count,Total Median Response Time,Total Average Response Time,Total Min Response Time,Total Max Response Time,Total Average Content Size
108,1789131768,4,POST,attacker,0.6,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
109,1789131768,4,POST,legitimate,4.7,0.0,230.0,240.0,240.0,250.0,...,300.0,300.0,300.0,176,0,220,256.350853,196.388284,1146.079165,870.000000
110,1789131768,4,NaN,Aggregated,5.3,0.0,230.0,240.0,250.0,260.0,...,1800.0,1800.0,1800.0,190,0,230,382.434194,196.388284,3374.858091,961.663158
111,1789131769,4,POST,attacker,0.4,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
112,1789131769,4,POST,legitimate,4.8,0.0,220.0,230.0,240.0,250.0,...,300.0,300.0,300.0,179,0,220,255.586996,196.388284,1146.079165,870.000000
113,1789131769,4,NaN,Aggregated,5.2,0.0,230.0,240.0,250.0,260.0,...,1800.0,1800.0,1800.0,193,0,230,379.765902,196.388284,3374.858091,960.238342
114,1789131770,4,POST,attacker,0.4,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
115,1789131770,4,POST,legitimate,4.6,0.0,220.0,230.0,240.0,250.0,...,300.0,300.0,300.0,183,0,220,254.499289,196.388284,1146.079165,870.000000
116,1789131770,4,NaN,Aggregated,5.0,0.0,220.0,230.0,250.0,250.0,...,1800.0,1800.0,1800.0,197,0,230,376.234095,196.388284,3374.858091,958.406091
117,1789131771,4,POST,attacker,0.4,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
118,1789131771,4,POST,legitimate,4.6,0.0,220.0,230.0,240.0,250.0,...,300.0,300.0,300.0,187,0,220,253.503963,196.388284,1146.079165,870.000000
119,1789131771,4,NaN,Aggregated,5.0,0.0,220.0,230.0,250.0,250.0,...,1800.0,1800.0,1800.0,201,0,220,372.885513,196.388284,3374.858091,956.646766
120,1789131772,4,POST,attacker,0.4,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
121,1789131772,4,POST,legitimate,4.5,0.0,210.0,230.0,250.0,250.0,...,300.0,300.0,300.0,189,0,220,252.950777,196.388284,1146.079165,870.000000
122,1789131772,4,NaN,Aggregated,4.9,0.0,220.0,230.0,250.0,260.0,...,1800.0,1800.0,1800.0,203,0,220,371.194304,196.388284,3374.858091,955.793103
123,1789131773,4,POST,attacker,0.4,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
124,1789131773,4,POST,legitimate,4.5,0.0,210.0,220.0,230.0,250.0,...,300.0,300.0,300.0,192,0,220,252.211244,196.388284,1146.079165,870.000000
125,1789131773,4,NaN,Aggregated,4.9,0.0,210.0,230.0,250.0,260.0,...,1800.0,1800.0,1800.0,206,0,220,368.783037,196.388284,3374.858091,954.543689
126,1789131774,4,POST,attacker,0.2,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
127,1789131774,4,POST,legitimate,4.0,0.0,210.0,210.0,220.0,220.0,...,270.0,270.0,270.0,197,0,220,250.942471,196.388284,1146.079165,870.000000
128,1789131774,4,NaN,Aggregated,4.2,0.0,210.0,210.0,220.0,220.0,...,270.0,270.0,270.0,211,0,220,364.836084,196.388284,3374.858091,952.540284
129,1789131775,4,POST,attacker,0.2,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
130,1789131775,4,POST,legitimate,3.9,0.0,210.0,210.0,210.0,220.0,...,270.0,270.0,270.0,202,0,210,249.742885,196.388284,1146.079165,870.000000
131,1789131775,4,NaN,Aggregated,4.1,0.0,210.0,210.0,210.0,220.0,...,270.0,270.0,270.0,216,0,220,361.077822,196.388284,3374.858091,950.629630
132,1789131776,4,POST,attacker,0.2,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
133,1789131776,4,POST,legitimate,3.9,0.0,210.0,210.0,210.0,210.0,...,230.0,230.0,230.0,204,0,210,249.420284,196.388284,1146.079165,870.000000
134,1789131776,4,NaN,Aggregated,4.1,0.0,210.0,210.0,210.0,210.0,...,230.0,230.0,230.0,218,0,220,359.754517,196.388284,3374.858091,949.889908
135,1789131777,4,POST,attacker,0.0,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,14,0,1800,1967.481917,1761.399410,3374.858091,2114.000000
136,1789131777,4,POST,legitimate,4.0,0.0,210.0,210.0,210.0,210.0,...,220.0,220.0,220.0,208,0,210,248.690992,196.388284,1146.079165,870.000000
137,1789131777,4,NaN,Aggregated,4.0,0.0,210.0,210.0,210.0,210.0,...,220.0,220.0,220.0,222,0,220,357.083212,196.388284,3374.858091,948.450450