<a href="https://colab.research.google.com/github/mena-04/DoS-Stress-Testing/blob/main/testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!nvidia-smi
!pip uninstall -y torch torchvision torchaudio vllm
!pip install -q -U uv
!uv pip install --system vllm --torch-backend=cu130

print("vLLM:", vllm.__version__)
print("Torch:", torch.__version__)
print("Torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

Fri Sep 11 13:59:36 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Found existing installation: torch 2.11.0+cu128
Uninstalling torch-2.11.0+cu128:
  Successfully uninstalled torch-2.11.0+cu128
Found existing installation: torchvision 0.26.0+cu128
Uninstalling torchvision-0.26.0+cu128:
  Successfully uninstalled torchvision-0.26.0+cu128
Found existing installation: torchaudio 2.11.0+cu128
Uninstalling torchaudio-2.11.0+cu128:
  Successfully uninstalled torchaudio-2.11.0+cu128
WARNING: Skipping vllm as it is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 87.5 MB/s eta 0:00:00
Using Python 3.13.15 environment at: /usr
Resolved 197 packages in 2.72s
Prepared 101 packages in 1m 18s
Uninstalled 13 packages in 119ms
Installed 101 packages in 864ms
 + agent-detector==2.0.0
 + anthropic==1.5.0
 + apache-tvm-ffi==0.1.11
 + astor==0.8.1
 + blake3==1.0.9
 + cbor2==6.1.4
 + compressed-tensors==0.17.0
 - cuda-bindings==12.9.7
 + cuda-bindings==13.4.1
 - cuda-core==0.3.2
 + cuda-core==1.2.0
 - cuda-python==12.9.7
 + cuda-python==13.4.1
 + cuda-tile==1.6.0
 - cuda-toolkit==12.8.1
 + cuda-toolkit==13.0.3.0
 + depyf==0.20.0
 + detect-installer==0.2.1
 + dnspython==2.8.0
 + email-validator==2.3.0
 - fastapi==0.141.1
 + fastapi==0.136.3
 + fastapi-cli==0.0.32
 + fastapi-cloud-cli==0.26.0
 + fastar==0.12.0
 + fastsafetensors==0.4.0
 + flashinfer-python==0.6.18
 + humming-kernels==0.1.12
 + ijson==3.5.1
 + instanttensor==0.1.9
 + interegular==0.3.3
 + jmespath==1.1.0
 - lark==1.3.1
 + lark==1.2.2
 + llguidance==1.7.6
 - llvmlite==0.44.0
 + llvmlite==0.47.0
 + lm-format-enforcer==0.11.3
 + loguru==0.7.3
 + mcp==2.2.0
 + mcp-types==2.2.0
 + mistral-common==1.11.7
 + model-hosting-container-standards==0.1.16
 + msgspec==0.21.1
 + nccl4py==0.5.0
 + ninja==1.13.2
 - numba==0.61.2
 + numba==0.65.0
 + nvidia-cublas==13.1.1.3
 + nvidia-cuda-cccl==13.3.4.2.1
 + nvidia-cuda-crt==13.4.59
 + nvidia-cuda-cupti==13.0.85
 + nvidia-cuda-nvcc==13.4.59
 + nvidia-cuda-nvdisasm==13.4.49
 + nvidia-cuda-nvrtc==13.0.88
 + nvidia-cuda-runtime==13.0.96
 + nvidia-cudnn-cu13==9.20.0.48
 + nvidia-cudnn-frontend==1.28.0
 + nvidia-cufft==12.0.0.61
 + nvidia-cufile==1.15.1.6
 + nvidia-curand==10.4.0.35
 + nvidia-cusolver==12.0.4.66
 + nvidia-cusparse==12.6.3.3
 + nvidia-cusparselt-cu13==0.8.1
 + nvidia-cutlass-dsl==4.6.2
 + nvidia-cutlass-dsl-libs-base==4.6.2
 + nvidia-cutlass-dsl-libs-core==4.6.2
 + nvidia-cutlass-dsl-libs-cu12==4.6.2
 + nvidia-cutlass-dsl-libs-cu13==4.6.2
 - nvidia-nccl-cu13==2.31.2
 + nvidia-nccl-cu13==2.29.7
 + nvidia-nvjitlink==13.4.52
 + nvidia-nvshmem-cu13==3.4.5
 + nvidia-nvtx==13.0.85
 + nvidia-nvvm==13.4.59
 - nvtx==0.2.16
 + nvtx==0.2.15
 + openai-harmony==0.0.8
 + opentelemetry-exporter-otlp==1.42.1
 + opentelemetry-exporter-otlp-proto-common==1.42.1
 + opentelemetry-exporter-otlp-proto-grpc==1.42.1
 + opentelemetry-exporter-otlp-proto-http==1.42.1
 + opentelemetry-proto==1.42.1
 + opentelemetry-semantic-conventions-ai==0.5.1
 + outlines-core==0.2.14
 + partial-json-parser==0.2.1.1.post7
 + prometheus-fastapi-instrumentator==8.1.0
 - protobuf==5.29.6
 + protobuf==6.33.6
 + pybase64==1.5.0
 + pycountry==26.2.16
 + pydantic-extra-types==2.11.1
 + pydantic-settings==2.15.0
 + pynvvideocodec==2.0.4
 + quack-kernels==0.6.4
 + rich-toolkit==0.20.5
 + rignore==0.8.1
 + setproctitle==1.3.7
 + sse-starlette==3.4.11
 + supervisor==4.3.0
 + tilelang==0.1.12
 + tokenspeed-mla==0.1.8
 + tokenspeed-triton==3.8.10.post20260906
 + torch==2.13.0+cu130
 + torch-c-dlpack-ext==0.1.5
 + torchaudio==2.11.0+cu130
 - torchcodec==0.11.0+cu128
 + torchcodec==0.16.0+cu130
 + torchvision==0.28.0+cu130
 - triton==3.6.0
 + triton==3.7.1
 + vllm==0.29.0
 + xgrammar==0.2.6
 + z3-solver==4.15.4.0

ImportError: libcudart.so.13: cannot open shared object file: No such file or directory

In [1]:
import torch
import vllm

print("vLLM:", vllm.__version__)
print("Torch:", torch.__version__)
print("Torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

vLLM: 0.29.0
Torch: 2.13.0+cu130
Torch CUDA: 13.0
CUDA available: True
GPU: Tesla T4

In [2]:
import importlib.util

print("torchaudio installed:",
      importlib.util.find_spec("torchaudio") is not None)

torchaudio installed: True

In [3]:
!pip uninstall -y torchaudio

Found existing installation: torchaudio 2.11.0+cu130
Uninstalling torchaudio-2.11.0+cu130:
  Successfully uninstalled torchaudio-2.11.0+cu130

In [4]:
import subprocess, time, requests, os, signal

# Stop old server if it exists
try:
    server.terminate()
    server.wait(timeout=10)
except:
    pass

log = open("/content/vllm.log", "w")

server = subprocess.Popen(
    [
        "vllm", "serve",
        "Qwen/Qwen2.5-0.5B-Instruct",
        "--dtype", "half",
        "--max-model-len", "2048",
        "--gpu-memory-utilization", "0.85",
        "--max-num-seqs", "8",
        "--host", "127.0.0.1",
        "--port", "8000",
    ],
    stdout=log,
    stderr=subprocess.STDOUT,
)

print("PID:", server.pid)

PID: 6060

In [5]:
for i in range(90):
    if server.poll() is not None:
        print("SERVER PROCESS EXITED")
        break

    try:
        r = requests.get(
            "http://127.0.0.1:8000/health",
            timeout=2
        )
        if r.status_code == 200:
            print("vLLM READY")
            break
    except:
        pass

    time.sleep(2)

vLLM READY

In [ ]:
!tail -n 100 /content/vllm.log

(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]        █     █     █▄   ▄█
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]  ▄▄ ▄█ █     █     █ ▀▄▀ █  version 0.29.0
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]   █▄█▀ █     █     █     █  model   Qwen/Qwen2.5-0.5B-Instruct
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]    ▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ▀     ▀
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:347]
(APIServer pid=9154) INFO 09-11 10:53:03 [api_utils.py:286] non-default args: {'model_tag': 'Qwen/Qwen2.5-0.5B-Instruct', 'host': '127.0.0.1', 'model': 'Qwen/Qwen2.5-0.5B-Instruct', 'dtype': 'half', 'max_model_len': 2048, 'gpu_memory_utilization': 0.85}
(APIServer pid=9154) Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
(APIServer pid=9154) INFO 09-11 10:53:19 [model.py:684] Resolved architecture: Qwen2ForCausalLM
(APIServer pid=9154) WARNING 09-11 10:53:19 [model.py:2355] Casting torch.bfloat16 to torch.float16.
(APIServer pid=9154) INFO 09-11 10:53:19 [model.py:2021] Using max model len 2048
(APIServer pid=9154) INFO 09-11 10:53:20 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(EngineCore pid=9336) INFO 09-11 10:53:40 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='Qwen/Qwen2.5-0.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-0.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=Qwen/Qwen2.5-0.5B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [2048], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')
(EngineCore pid=9336) INFO 09-11 10:53:44 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_6cb5f4d5ed704f729fa2ccea4e614b2a backend=nccl
(EngineCore pid=9336) INFO 09-11 10:53:44 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=9336) INFO 09-11 10:53:44 [gpu_worker.py:429] Using V2 Model Runner
(EngineCore pid=9336) INFO 09-11 10:53:46 [model_runner.py:382] Loading model from scratch...
(EngineCore pid=9336) ERROR 09-11 10:53:47 [fa_utils.py:212] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
(EngineCore pid=9336) INFO 09-11 10:53:53 [cuda.py:492] Using TRITON_ATTN attention backend out of potential backends: ['TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=9336) INFO 09-11 10:54:07 [weight_utils.py:526] Time spent downloading weights for Qwen/Qwen2.5-0.5B-Instruct: 13.148929 seconds
(EngineCore pid=9336) INFO 09-11 10:54:07 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 0.92 GiB. Available RAM: 8.67 GiB.
(EngineCore pid=9336) INFO 09-11 10:54:07 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:01<00:00,  1.04s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:01<00:00,  1.04s/it]
(EngineCore pid=9336)
(EngineCore pid=9336) INFO 09-11 10:54:08 [default_loader.py:430] Loading weights took 1.08 seconds
(EngineCore pid=9336) INFO 09-11 10:54:09 [model_runner.py:404] Model loading took 0.93 GiB memory and 24.048326 seconds
(EngineCore pid=9336) WARNING 09-11 10:54:09 [topk_topp_sampler.py:69] FlashInfer top-p/top-k sampling unavailable: unsupported compute capability 7.5; falling back. Set VLLM_USE_FLASHINFER_SAMPLER=0 to silence.
(EngineCore pid=9336) INFO 09-11 10:54:09 [utils.py:306] Using LBNHC KV cache layout.
(EngineCore pid=9336) INFO 09-11 10:54:20 [backends.py:1094] Using cache directory: /root/.cache/vllm/torch_compile_cache/013f3c2783/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=9336) INFO 09-11 10:54:20 [backends.py:1155] Dynamo bytecode transform time: 7.59 s
(EngineCore pid=9336) [rank0]:W0911 10:54:26.410000 9336 torch/_inductor/utils.py:1953] Not enough SMs to use max_autotune_gemm mode
(EngineCore pid=9336) INFO 09-11 10:54:29 [backends.py:393] Compiling a graph for compile range (1, 2048) takes 9.14 s
(EngineCore pid=9336) INFO 09-11 10:54:34 [backends.py:920] collected artifacts: 25 entries, 3 artifacts, 4806285 bytes total
(EngineCore pid=9336) INFO 09-11 10:54:34 [decorators.py:719] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/31270efa7481fb75c29d5500267756330968687c2b2ebe7da3dc9fda50a9ce26/rank_0_0/model
(EngineCore pid=9336) INFO 09-11 10:54:34 [monitor.py:53] torch.compile took 21.13 s in total
(EngineCore pid=9336) INFO 09-11 10:54:34 [monitor.py:81] Initial profiling/warmup run took 0.13 s
Capturing CUDA graphs (PIECEWISE): 100%|██████████| 51/51 [00:05<00:00,  8.86it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 23.73it/s]
(EngineCore pid=9336) INFO 09-11 10:54:43 [model_runner.py:960] Graph capturing finished in 6 secs, took 0.24 GiB
(EngineCore pid=9336) INFO 09-11 10:54:43 [gpu_worker.py:625] Available KV cache memory: 10.4 GiB
(EngineCore pid=9336) INFO 09-11 10:54:43 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.8500 is equivalent to --gpu-memory-utilization=0.8308 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.8692. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=9336) INFO 09-11 10:54:43 [kv_cache_utils.py:2032] GPU KV cache size: 908,704 tokens, Maximum concurrency for 2,048 tokens per request: 443.70x
(EngineCore pid=9336) INFO 09-11 10:54:43 [kernel_warmup.py:124] JIT kernel warmup starting.
(EngineCore pid=9336) INFO 09-11 10:54:43 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.
Capturing CUDA graphs (PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 20.34it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 35/35 [00:01<00:00, 25.33it/s]
(EngineCore pid=9336) INFO 09-11 10:54:51 [model_runner.py:960] Graph capturing finished in 5 secs, took 0.13 GiB
(EngineCore pid=9336) INFO 09-11 10:54:51 [gpu_worker.py:797] CUDA graph pool memory: 0.13 GiB (actual), 0.28 GiB (estimated), difference: 0.15 GiB (120.0%).
(EngineCore pid=9336) INFO 09-11 10:54:51 [gpu_worker.py:860] Free memory on device (14.46/14.56 GiB) on startup. Desired GPU memory utilization is (0.85, 12.38 GiB). Actual usage is 1.45 GiB for consumed memory (weights + non-torch), 0.53 GiB for peak activation, and 0.13 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=10872573645` (10.13 GiB) to fit into requested memory, or `--kv-cache-memory=13108167168` (12.21 GiB) to fully utilize gpu memory. Current kv cache memory in use is 10.4 GiB.
(EngineCore pid=9336) INFO 09-11 10:55:01 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.
(EngineCore pid=9336) INFO 09-11 10:55:02 [core.py:361] init engine (profile, create kv cache, warmup model) took 52.76 s (compilation: 21.13 s)
(EngineCore pid=9336) Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
(EngineCore pid=9336) INFO 09-11 10:55:05 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(APIServer pid=9154) INFO 09-11 10:55:05 [entry.py:135] Supported tasks: ['generate']
(APIServer pid=9154) INFO 09-11 10:55:09 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
(APIServer pid=9154) WARNING 09-11 10:55:09 [model.py:1759] Default vLLM sampling parameters have been overridden by the model's `generation_config.json`: `{'repetition_penalty': 1.1, 'temperature': 0.7, 'top_k': 20, 'top_p': 0.8}`. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
(APIServer pid=9154) INFO 09-11 10:55:09 [entry.py:139] Starting vLLM server on http://127.0.0.1:8000
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:61] Available routes are:
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /openapi.json, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /docs, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /docs/oauth2-redirect, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /redoc, Methods: HEAD, GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /load, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /version, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /health, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /metrics, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /tokenize, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /detokenize, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/models, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /ping, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /ping, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /invocations, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions/batch, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/responses, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/responses/{response_id}, Methods: GET
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/responses/{response_id}/cancel, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/completions, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/messages, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/messages/count_tokens, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /generative_scoring, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /scale_elastic_ep, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /is_scaling_elastic_ep, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions/render, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/messages/render, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/completions/render, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/chat/completions/derender, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /v1/completions/derender, Methods: POST
(APIServer pid=9154) INFO 09-11 10:55:09 [launcher.py:70] Route: /inference/v1/generate, Methods: POST
(APIServer pid=9154) INFO:     Started server process [9154]
(APIServer pid=9154) INFO:     Waiting for application startup.
(APIServer pid=9154) INFO:     Application startup complete.
(APIServer pid=9154) INFO:     127.0.0.1:55432 - "GET /health HTTP/1.1" 200 OK

In [6]:
import requests
import time

URL = "http://127.0.0.1:8000/v1/chat/completions"

payload = {
    "model": "Qwen/Qwen2.5-0.5B-Instruct",
    "messages": [
        {
            "role": "user",
            "content": "Explain AI inference in one sentence."
        }
    ],
    "max_tokens": 32,
    "temperature": 0
}

start = time.perf_counter()

r = requests.post(
    URL,
    json=payload,
    timeout=60
)

elapsed = time.perf_counter() - start

print("status:", r.status_code)
print("latency:", round(elapsed, 3), "seconds")

data = r.json()

print("response:")
print(data["choices"][0]["message"]["content"])

print("usage:")
print(data["usage"])

status: 200
latency: 0.924 seconds
response:
AI inference involves processing and analyzing large amounts of data to make predictions or decisions based on patterns and relationships within that data.
usage:
{'prompt_tokens': 37, 'total_tokens': 62, 'completion_tokens': 25, 'prompt_tokens_details': None, 'completion_tokens_details': None}

In [7]:
m = requests.get(
    "http://127.0.0.1:8000/metrics",
    timeout=10
)

print("metrics status:", m.status_code)

wanted = [
    "vllm:num_requests_running",
    "vllm:num_requests_waiting",
    "vllm:request_success_total",
    "vllm:e2e_request_latency_seconds",
    "vllm:request_queue_time_seconds",
    "vllm:prompt_tokens_total",
    "vllm:generation_tokens_total",
]

for metric in wanted:
    print("\n---", metric, "---")
    for line in m.text.splitlines():
        if line.startswith(metric):
            print(line)

metrics status: 200

--- vllm:num_requests_running ---
vllm:num_requests_running{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0

--- vllm:num_requests_waiting ---
vllm:num_requests_waiting{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:num_requests_waiting_by_reason{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct",reason="capacity"} 0.0
vllm:num_requests_waiting_by_reason{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct",reason="deferred"} 0.0

--- vllm:request_success_total ---
vllm:request_success_total{engine="0",finished_reason="stop",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_success_total{engine="0",finished_reason="length",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:request_success_total{engine="0",finished_reason="abort",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:request_success_total{engine="0",finished_reason="error",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:request_success_total{engine="0",finished_reason="repetition",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0

--- vllm:e2e_request_latency_seconds ---
vllm:e2e_request_latency_seconds_bucket{engine="0",le="0.3",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="0.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="0.8",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="1.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="1.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="2.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="2.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="5.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="10.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="15.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="20.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="30.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="40.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="50.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="60.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="120.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="240.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="480.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="960.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="1920.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="7680.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_bucket{engine="0",le="+Inf",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_count{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:e2e_request_latency_seconds_sum{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 0.916588544845581
vllm:e2e_request_latency_seconds_created{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.789135473112377e+09

--- vllm:request_queue_time_seconds ---
vllm:request_queue_time_seconds_bucket{engine="0",le="0.3",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="0.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="0.8",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="1.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="1.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="2.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="2.5",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="5.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="10.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="15.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="20.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="30.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="40.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="50.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="60.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="120.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="240.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="480.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="960.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="1920.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="7680.0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_bucket{engine="0",le="+Inf",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_count{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.0
vllm:request_queue_time_seconds_sum{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 2.994000010403397e-05
vllm:request_queue_time_seconds_created{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 1.7891354731124456e+09

--- vllm:prompt_tokens_total ---
vllm:prompt_tokens_total{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 37.0

--- vllm:generation_tokens_total ---
vllm:generation_tokens_total{engine="0",model_name="Qwen/Qwen2.5-0.5B-Instruct"} 25.0

# background metrics sampler

In [8]:
import threading
import requests
import time
import re
import csv

stop_sampling = False
samples = []

def get_value(text, name):
    pattern = rf'^{re.escape(name)}\{{.*?\}}\s+([0-9.eE+-]+)'
    m = re.search(pattern, text, re.MULTILINE)
    return float(m.group(1)) if m else None

def sampler():
    while not stop_sampling:
        try:
            text = requests.get(
                "http://127.0.0.1:8000/metrics",
                timeout=2
            ).text

            samples.append({
                "timestamp": time.time(),
                "running": get_value(
                    text,
                    "vllm:num_requests_running"
                ),
                "waiting": get_value(
                    text,
                    "vllm:num_requests_waiting"
                )
            })
        except Exception:
            pass

        time.sleep(0.25)

thread = threading.Thread(target=sampler, daemon=True)
thread.start()

print("sampler started")

sampler started

# concurrent overload test

In [9]:
import asyncio
import aiohttp
import time
import statistics

URL = "http://127.0.0.1:8000/v1/chat/completions"
MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30

async def send_one(session, i):
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "user", "content": EXPENSIVE_PROMPT}
        ],
        "max_tokens": 256,
        "temperature": 0
    }

    start = time.perf_counter()

    try:
        async with session.post(URL, json=payload, timeout=120) as r:
            await r.text()
            latency = time.perf_counter() - start
            return {
                "id": i,
                "status": r.status,
                "latency": latency
            }
    except Exception as e:
        return {
            "id": i,
            "status": "error",
            "latency": time.perf_counter() - start
        }



async def run_load(n=50):
    async with aiohttp.ClientSession() as session:
        tasks = [
            asyncio.create_task(send_one(session, i))
            for i in range(n)
        ]
        return await asyncio.gather(*tasks)

results = await run_load(40)

latencies = [
    r["latency"]
    for r in results
    if r["status"] == 200
]

print("completed:", len(results))
print("successful:", len(latencies))

if latencies:
    print("p50:", round(statistics.median(latencies), 3))

    sorted_lat = sorted(latencies)
    p95_index = int(0.95 * len(sorted_lat)) - 1
    print("p95:", round(sorted_lat[p95_index], 3))

    print("max:", round(max(latencies), 3))

completed: 40
successful: 40
p50: 7.209
p95: 11.833
max: 11.834

In [10]:
stop_sampling = True
thread.join(timeout=2)

print("samples:", len(samples))
print("max running:", max(x["running"] or 0 for x in samples))
print("max waiting:", max(x["waiting"] or 0 for x in samples))

samples: 46
max running: 8.0
max waiting: 32.0

# Load generator

In [11]:
!pip install -q locust
!locust --version

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 68.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 86.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.4/115.4 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.3/60.3 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.6/270.6 kB 22.2 MB/s eta 0:00:00
locust 2.46.5 from /usr/local/lib/python3.13/dist-packages/locust (Python 3.13.15)

In [12]:
%%writefile /content/locustfile.py
# first testing with normal traffic
from locust import HttpUser, task, between
import random


MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 4

    @task
    def legitimate_request(self):
        payload = {
            "model": MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": SMALL_PROMPT
                }
            ],
            "max_tokens": 32,
            "temperature": 0
        }

        self.client.post(
            "/v1/chat/completions",
            json=payload,
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(0.05, 0.15)
    weight = 1

    @task
    def attack_request(self):
        payload = {
            "model": MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": EXPENSIVE_PROMPT
                }
            ],
            "max_tokens": 256,
            "temperature": 0
        }

        self.client.post(
            "/v1/chat/completions",
            json=payload,
            name="attacker"
        )

Writing /content/locustfile.py

In [13]:
!mkdir -p /content/results

In [14]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --users 4 \
  --spawn-rate 2 \
  --run-time 15s \
  --csv /content/results/normal \
  --csv-full-history \
  LegitimateUser

[2026-09-11 14:07:45,665] 626a8ef1d973/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 14:07:45,666] 626a8ef1d973/INFO/locust.main: Run time limit set to 15 seconds
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 14:07:45,668] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 2.00 per second
[2026-09-11 14:07:46,669] 626a8ef1d973/INFO/locust.runners: All users spawned: {"LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       7     0(0.00%) |    226     197     286    210 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       7     0(0.00%) |    226     197     286    210 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      13     0(0.00%) |    216     197     286    210 |    2.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      13     0(0.00%) |    216     197     286    210 |    2.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      21     0(0.00%) |    211     197     286    210 |    2.75        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      21     0(0.00%) |    211     197     286    210 |    2.75        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      28     0(0.00%) |    216     197     300    210 |    3.17        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      28     0(0.00%) |    216     197     300    210 |    3.17        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      34     0(0.00%) |    215     197     300    210 |    3.12        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      34     0(0.00%) |    215     197     300    210 |    3.12        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      41     0(0.00%) |    214     197     300    210 |    3.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      41     0(0.00%) |    214     197     300    210 |    3.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      47     0(0.00%) |    222     197     317    210 |    3.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      47     0(0.00%) |    222     197     317    210 |    3.40        0.00

[2026-09-11 14:08:00,409] 626a8ef1d973/INFO/locust.main: --run-time limit reached, shutting down
[2026-09-11 14:08:00,437] 626a8ef1d973/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      49     0(0.00%) |    221     197     317    210 |    3.33        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      49     0(0.00%) |    221     197     317    210 |    3.33        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     legitimate      210    210    220    250    290    300    320    320    320    320    320     49
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated      210    210    220    250    290    300    320    320    320    320    320     49

In [15]:
import pandas as pd

df = pd.read_csv("/content/results/normal_stats.csv")
display(df)

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,legitimate,47,0,210,222.495028,197.791084,317.907559,870.0,3.356832,...,210,220,250,290,300,320,320,320,320,320
1,NaN,Aggregated,47,0,210,222.495028,197.791084,317.907559,870.0,3.356832,...,210,220,250,290,300,320,320,320,320,320

In [16]:
%%writefile /content/locustfile.py
# sudden spike
from locust import HttpUser, task, between, LoadTestShape

MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 1

    @task
    def legitimate_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": SMALL_PROMPT
                    }
                ],
                "max_tokens": 32,
                "temperature": 0
            },
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(0.05, 0.15)
    weight = 1

    @task
    def attack_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": MEDIUM_PROMPT
                    }
                ],
                "max_tokens": 128,
                "temperature": 0
            },
            name="attacker"
        )


class SpikeShape(LoadTestShape):

    def tick(self):
        run_time = self.get_run_time()

        # 0-10s: legitimate traffic only
        if run_time < 10:
            return (
                4,
                4,
                [LegitimateUser]
            )

        # 10-20s: sudden attacker spike
        if run_time < 20:
            return (
                24,
                20,
                [LegitimateUser, AttackerUser]
            )

        # 20-30s: attack stops, return to normal
        if run_time < 30:
            return (
                4,
                20,
                [LegitimateUser]
            )

        return None

Overwriting /content/locustfile.py

In [17]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --csv /content/results/spike \
  --csv-full-history

[2026-09-11 14:08:02,913] 626a8ef1d973/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 14:08:02,914] 626a8ef1d973/INFO/locust.runners: Shape test starting.
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 14:08:02,915] 626a8ef1d973/INFO/locust.runners: Shape worker starting
[2026-09-11 14:08:02,915] 626a8ef1d973/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 14:08:02,916] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 14:08:02,916] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       8     0(0.00%) |    241     202     284    210 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       8     0(0.00%) |    241     202     284    210 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      16     0(0.00%) |    221     196     284    200 |    2.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      16     0(0.00%) |    221     196     284    200 |    2.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      23     0(0.00%) |    223     196     284    210 |    3.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      23     0(0.00%) |    223     196     284    210 |    3.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      29     0(0.00%) |    220     196     284    210 |    3.17        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      29     0(0.00%) |    220     196     284    210 |    3.17        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      36     0(0.00%) |    216     196     284    210 |    3.38        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      36     0(0.00%) |    216     196     284    210 |    3.38        0.00

[2026-09-11 14:08:12,927] 626a8ef1d973/INFO/locust.runners: Shape test updating to 24 users at 20.00 spawn rate
[2026-09-11 14:08:12,927] 626a8ef1d973/INFO/locust.runners: Ramping to 24 users at a rate of 20.00 per second
[2026-09-11 14:08:12,929] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 10, "LegitimateUser": 14} (24 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      10     0(0.00%) |   1188     973    1911   1000 |    0.00        0.00
POST     legitimate      50     0(0.00%) |    472     196    1450    210 |    3.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      60     0(0.00%) |    591     196    1911    240 |    3.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      24     0(0.00%) |   1303     973    1911   1300 |    0.70        0.00
POST     legitimate      65     0(0.00%) |    517     196    1450    250 |    3.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      89     0(0.00%) |    729     196    1911    620 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      36     0(0.00%) |   1353     973    1911   1300 |    1.80        0.00
POST     legitimate      82     0(0.00%) |    562     196    1450    500 |    4.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     118     0(0.00%) |    803     196    1911    770 |    6.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      50     0(0.00%) |   1395     973    1911   1400 |    3.00        0.00
POST     legitimate      97     0(0.00%) |    604     196    1450    650 |    5.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     147     0(0.00%) |    873     196    1911    850 |    8.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1420     973    1911   1400 |    4.30        0.00
POST     legitimate     112     0(0.00%) |    624     196    1450    680 |    6.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     174     0(0.00%) |    908     196    1911    860 |   10.60        0.00

[2026-09-11 14:08:22,944] 626a8ef1d973/INFO/locust.runners: Shape test updating to 4 users at 20.00 spawn rate
[2026-09-11 14:08:22,944] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 20.00 per second
[2026-09-11 14:08:22,953] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      63     0(0.00%) |   1417     973    1911   1400 |    5.60        0.00
POST     legitimate     120     0(0.00%) |    608     196    1450    680 |    7.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     183     0(0.00%) |    886     196    1911    850 |   13.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      63     0(0.00%) |   1417     973    1911   1400 |    5.60        0.00
POST     legitimate     127     0(0.00%) |    585     196    1450    620 |    8.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     190     0(0.00%) |    861     196    1911    840 |   13.60        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      63     0(0.00%) |   1417     973    1911   1400 |    4.50        0.00
POST     legitimate     133     0(0.00%) |    568     196    1450    590 |    6.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     196     0(0.00%) |    841     196    1911    820 |   11.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      63     0(0.00%) |   1417     973    1911   1400 |    3.30        0.00
POST     legitimate     139     0(0.00%) |    553     196    1450    520 |    5.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     202     0(0.00%) |    822     196    1911    790 |    9.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      63     0(0.00%) |   1417     973    1911   1400 |    2.00        0.00
POST     legitimate     147     0(0.00%) |    535     196    1450    480 |    4.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     210     0(0.00%) |    800     196    1911    770 |    6.50        0.00

[2026-09-11 14:08:32,960] 626a8ef1d973/INFO/locust.runners: Shape test stopping
[2026-09-11 14:08:32,991] 626a8ef1d973/INFO/locust.main: Shape test completed, shutting down
[2026-09-11 14:08:32,991] 626a8ef1d973/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      63     0(0.00%) |   1417     973    1911   1400 |    2.10        0.00
POST     legitimate     147     0(0.00%) |    535     196    1450    480 |    4.90        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     210     0(0.00%) |    800     196    1911    770 |    7.00        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     attacker     1400   1500   1600   1600   1700   1700   1900   1900   1900   1900   1900     63
POST     legitimate      480    720    800    850    960   1200   1400   1400   1500   1500   1500    147
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated      770   1000   1300   1400   1500   1700   1700   1800   1900   1900   1900    210

In [18]:
import pandas as pd

df = pd.read_csv("/content/results/spike_stats.csv")
display(df)

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,attacker,63,0,1400,1417.387815,973.886594,1911.976599,1414.0,2.100442,...,1500,1600,1600,1700,1700,1900,1900,1900,1900,1900
1,POST,legitimate,147,0,480,535.533176,196.823806,1450.673655,870.0,4.901032,...,720,800,850,960,1200,1400,1400,1500,1500,1500
2,NaN,Aggregated,210,0,770,800.089567,196.823806,1911.976599,1033.2,7.001475,...,1000,1300,1400,1500,1700,1700,1800,1900,1900,1900

In [19]:
hist = pd.read_csv("/content/results/spike_stats_history.csv")

display(hist.tail(20))

,Timestamp,User Count,Type,Name,Requests/s,Failures/s,50%,66%,75%,80%,...,99.9%,99.99%,100%,Total Request Count,Total Failure Count,Total Median Response Time,Total Average Response Time,Total Min Response Time,Total Max Response Time,Total Average Content Size
61,1789135706,4,POST,legitimate,8.0,0.0,730.0,790.0,840.0,850.0,...,1000.0,1000.0,1000.0,127,0,620.0,585.937106,196.823806,1450.673655,870.000000
62,1789135706,4,NaN,Aggregated,13.6,0.0,860.0,1300.0,1400.0,1500.0,...,1700.0,1700.0,1700.0,190,0,840.0,861.628656,196.823806,1911.976599,1050.378947
63,1789135707,4,POST,attacker,5.3,0.0,1500.0,1500.0,1600.0,1600.0,...,1700.0,1700.0,1700.0,63,0,1400.0,1417.387815,973.886594,1911.976599,1414.000000
64,1789135707,4,POST,legitimate,7.1,0.0,730.0,820.0,850.0,860.0,...,1000.0,1000.0,1000.0,130,0,590.0,577.104274,196.823806,1450.673655,870.000000
65,1789135707,4,NaN,Aggregated,12.4,0.0,860.0,1200.0,1400.0,1500.0,...,1700.0,1700.0,1700.0,193,0,830.0,851.393720,196.823806,1911.976599,1047.575130
66,1789135708,4,POST,attacker,4.5,0.0,1500.0,1600.0,1600.0,1700.0,...,1700.0,1700.0,1700.0,63,0,1400.0,1417.387815,973.886594,1911.976599,1414.000000
67,1789135708,4,POST,legitimate,6.6,0.0,680.0,770.0,840.0,860.0,...,1000.0,1000.0,1000.0,133,0,590.0,568.906093,196.823806,1450.673655,870.000000
68,1789135708,4,NaN,Aggregated,11.1,0.0,850.0,1200.0,1400.0,1500.0,...,1700.0,1700.0,1700.0,196,0,820.0,841.632361,196.823806,1911.976599,1044.857143
69,1789135709,4,POST,attacker,3.8,0.0,1600.0,1600.0,1700.0,1700.0,...,1700.0,1700.0,1700.0,63,0,1400.0,1417.387815,973.886594,1911.976599,1414.000000
70,1789135709,4,POST,legitimate,6.2,0.0,590.0,720.0,820.0,870.0,...,1000.0,1000.0,1000.0,135,0,560.0,563.543834,196.823806,1450.673655,870.000000
71,1789135709,4,NaN,Aggregated,10.0,0.0,770.0,970.0,1400.0,1500.0,...,1700.0,1700.0,1700.0,198,0,800.0,835.221464,196.823806,1911.976599,1043.090909
72,1789135710,4,POST,attacker,3.3,0.0,1600.0,1600.0,1700.0,1700.0,...,1700.0,1700.0,1700.0,63,0,1400.0,1417.387815,973.886594,1911.976599,1414.000000
73,1789135710,4,POST,legitimate,5.7,0.0,220.0,590.0,700.0,720.0,...,1000.0,1000.0,1000.0,139,0,520.0,553.462437,196.823806,1450.673655,870.000000
74,1789135710,4,NaN,Aggregated,9.0,0.0,590.0,770.0,1000.0,1200.0,...,1700.0,1700.0,1700.0,202,0,790.0,822.904510,196.823806,1911.976599,1039.663366
75,1789135711,4,POST,attacker,2.7,0.0,1600.0,1600.0,1700.0,1700.0,...,1700.0,1700.0,1700.0,63,0,1400.0,1417.387815,973.886594,1911.976599,1414.000000
76,1789135711,4,POST,legitimate,5.1,0.0,210.0,220.0,230.0,430.0,...,770.0,770.0,770.0,143,0,500.0,544.128172,196.823806,1450.673655,870.000000
77,1789135711,4,NaN,Aggregated,7.8,0.0,220.0,430.0,720.0,760.0,...,1700.0,1700.0,1700.0,206,0,770.0,811.193014,196.823806,1911.976599,1036.368932
78,1789135712,4,POST,attacker,2.0,0.0,1600.0,1600.0,1700.0,1700.0,...,1700.0,1700.0,1700.0,63,0,1400.0,1417.387815,973.886594,1911.976599,1414.000000
79,1789135712,4,POST,legitimate,4.5,0.0,210.0,220.0,220.0,220.0,...,720.0,720.0,720.0,147,0,480.0,535.533176,196.823806,1450.673655,870.000000
80,1789135712,4,NaN,Aggregated,6.5,0.0,210.0,220.0,220.0,220.0,...,720.0,720.0,720.0,210,0,770.0,800.089567,196.823806,1911.976599,1033.200000

In [20]:
%%writefile /content/locustfile.py
# sustained flood
from locust import HttpUser, task, between, LoadTestShape

MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 1

    @task
    def legitimate_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": SMALL_PROMPT
                    }
                ],
                "max_tokens": 32,
                "temperature": 0
            },
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(0.05, 0.15)
    weight = 1

    @task
    def attack_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": MEDIUM_PROMPT
                    }
                ],
                "max_tokens": 128,
                "temperature": 0
            },
            name="attacker"
        )


class FloodShape(LoadTestShape):

    def tick(self):
        run_time = self.get_run_time()

        # 0-10s: normal legitimate traffic
        if run_time < 10:
            return (
                4,
                4,
                [LegitimateUser]
            )

        # 10-40s: sustained flood
        if run_time < 40:
            return (
                32,
                20,
                [LegitimateUser, AttackerUser]
            )

        # 40-50s: recovery
        if run_time < 50:
            return (
                4,
                20,
                [LegitimateUser]
            )

        return None

Overwriting /content/locustfile.py

In [21]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --csv /content/results/flood \
  --csv-full-history

[2026-09-11 14:08:35,177] 626a8ef1d973/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 14:08:35,178] 626a8ef1d973/INFO/locust.runners: Shape test starting.
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 14:08:35,179] 626a8ef1d973/INFO/locust.runners: Shape worker starting
[2026-09-11 14:08:35,179] 626a8ef1d973/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 14:08:35,179] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 14:08:35,180] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      10     0(0.00%) |    229     205     267    210 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      10     0(0.00%) |    229     205     267    210 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      16     0(0.00%) |    222     205     267    210 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      16     0(0.00%) |    222     205     267    210 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      23     0(0.00%) |    218     200     267    210 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      23     0(0.00%) |    218     200     267    210 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      29     0(0.00%) |    217     200     267    210 |    3.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      29     0(0.00%) |    217     200     267    210 |    3.80        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      35     0(0.00%) |    216     200     267    210 |    3.62        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      35     0(0.00%) |    216     200     267    210 |    3.62        0.00

[2026-09-11 14:08:45,192] 626a8ef1d973/INFO/locust.runners: Shape test updating to 32 users at 20.00 spawn rate
[2026-09-11 14:08:45,192] 626a8ef1d973/INFO/locust.runners: Ramping to 32 users at a rate of 20.00 per second
[2026-09-11 14:08:46,195] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 14, "LegitimateUser": 18} (32 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       8     0(0.00%) |   1155    1084    1374   1100 |    0.00        0.00
POST     legitimate      51     0(0.00%) |    508     200    1605    220 |    3.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      59     0(0.00%) |    595     200    1605    220 |    3.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      22     0(0.00%) |   1651    1084    2473   1600 |    0.80        0.00
POST     legitimate      61     0(0.00%) |    639     200    1684    230 |    4.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      83     0(0.00%) |    907     200    2473   1100 |    4.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      35     0(0.00%) |   1780    1084    2473   1800 |    2.10        0.00
POST     legitimate      78     0(0.00%) |    800     200    1684    720 |    4.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     113     0(0.00%) |   1103     200    2473   1200 |    6.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      49     0(0.00%) |   1864    1084    2473   2000 |    3.50        0.00
POST     legitimate      94     0(0.00%) |    902     200    1684   1200 |    5.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     143     0(0.00%) |   1231     200    2473   1400 |    8.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      62     0(0.00%) |   1910    1084    2473   2100 |    4.80        0.00
POST     legitimate     110     0(0.00%) |    978     200    1684   1300 |    6.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     172     0(0.00%) |   1314     200    2473   1400 |   11.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      74     0(0.00%) |   1933    1084    2473   2100 |    6.00        0.00
POST     legitimate     124     0(0.00%) |   1028     200    1758   1300 |    7.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     198     0(0.00%) |   1366     200    2473   1400 |   13.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      84     0(0.00%) |   1965    1084    2473   2100 |    6.20        0.00
POST     legitimate     139     0(0.00%) |   1095     200    1910   1400 |    7.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     223     0(0.00%) |   1423     200    2473   1500 |   13.60        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      98     0(0.00%) |   2046    1084    2693   2100 |    6.30        0.00
POST     legitimate     152     0(0.00%) |   1151     200    1948   1400 |    7.60        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     250     0(0.00%) |   1502     200    2693   1600 |   13.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     111     0(0.00%) |   2044    1084    2693   2100 |    6.20        0.00
POST     legitimate     166     0(0.00%) |   1177     200    1948   1400 |    7.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     277     0(0.00%) |   1525     200    2693   1600 |   13.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     121     0(0.00%) |   2050    1084    2693   2100 |    5.90        0.00
POST     legitimate     181     0(0.00%) |   1199     200    1948   1400 |    7.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     302     0(0.00%) |   1540     200    2693   1600 |   13.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     133     0(0.00%) |   2060    1084    2693   2100 |    5.90        0.00
POST     legitimate     196     0(0.00%) |   1216     200    1948   1400 |    7.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     329     0(0.00%) |   1557     200    2693   1600 |   13.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     146     0(0.00%) |   2064    1084    2693   2100 |    6.20        0.00
POST     legitimate     211     0(0.00%) |   1231     200    1948   1400 |    7.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     357     0(0.00%) |   1571     200    2693   1600 |   13.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     159     0(0.00%) |   2077    1084    2693   2100 |    6.20        0.00
POST     legitimate     226     0(0.00%) |   1254     200    1948   1400 |    7.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     385     0(0.00%) |   1594     200    2693   1600 |   13.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     170     0(0.00%) |   2098    1084    2693   2100 |    6.10        0.00
POST     legitimate     239     0(0.00%) |   1272     200    1948   1400 |    7.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     409     0(0.00%) |   1615     200    2693   1600 |   13.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     181     0(0.00%) |   2107    1084    2693   2100 |    6.20        0.00
POST     legitimate     255     0(0.00%) |   1284     200    1948   1400 |    7.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     436     0(0.00%) |   1626     200    2693   1600 |   13.70        0.00

[2026-09-11 14:09:15,243] 626a8ef1d973/INFO/locust.runners: Shape test updating to 4 users at 20.00 spawn rate
[2026-09-11 14:09:15,243] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 20.00 per second
[2026-09-11 14:09:16,248] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     187     0(0.00%) |   2096     894    2693   2100 |    6.10        0.00
POST     legitimate     266     0(0.00%) |   1249     200    1948   1400 |    7.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     453     0(0.00%) |   1599     200    2693   1600 |   13.80        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     187     0(0.00%) |   2096     894    2693   2100 |    5.50        0.00
POST     legitimate     273     0(0.00%) |   1223     200    1948   1400 |    7.20        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     460     0(0.00%) |   1578     200    2693   1600 |   12.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     187     0(0.00%) |   2096     894    2693   2100 |    4.10        0.00
POST     legitimate     280     0(0.00%) |   1198     200    1948   1400 |    6.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     467     0(0.00%) |   1557     200    2693   1600 |   10.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     187     0(0.00%) |   2096     894    2693   2100 |    3.50        0.00
POST     legitimate     286     0(0.00%) |   1178     200    1948   1400 |    5.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     473     0(0.00%) |   1541     200    2693   1600 |    9.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     187     0(0.00%) |   2096     894    2693   2100 |    1.80        0.00
POST     legitimate     292     0(0.00%) |   1158     200    1948   1400 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     479     0(0.00%) |   1524     200    2693   1600 |    6.60        0.00

[2026-09-11 14:09:25,260] 626a8ef1d973/INFO/locust.runners: Shape test stopping
[2026-09-11 14:09:25,286] 626a8ef1d973/INFO/locust.main: Shape test completed, shutting down
[2026-09-11 14:09:25,287] 626a8ef1d973/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker     187     0(0.00%) |   2096     894    2693   2100 |    3.75        0.00
POST     legitimate     292     0(0.00%) |   1158     200    1948   1400 |    5.86        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     479     0(0.00%) |   1524     200    2693   1600 |    9.61        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     attacker     2100   2200   2300   2300   2400   2500   2600   2600   2700   2700   2700    187
POST     legitimate     1400   1500   1600   1600   1700   1800   1800   1900   1900   1900   1900    292
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated     1600   1900   2100   2100   2300   2400   2500   2600   2700   2700   2700    479

In [22]:
import pandas as pd

df = pd.read_csv("/content/results/flood_stats.csv")
display(df)

hist = pd.read_csv("/content/results/flood_stats_history.csv")
display(hist.tail(30))

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,attacker,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963,3.753275,...,2200,2300,2300,2400,2500,2600,2600,2700,2700,2700
1,POST,legitimate,292,0,1400,1158.508394,200.183667,1948.905035,870.000000,5.860728,...,1500,1600,1600,1700,1800,1800,1900,1900,1900,1900
2,NaN,Aggregated,479,0,1600,1524.567192,200.183667,2693.519002,1082.321503,9.614003,...,1900,2100,2100,2300,2400,2500,2600,2700,2700,2700

,Timestamp,User Count,Type,Name,Requests/s,Failures/s,50%,66%,75%,80%,...,99.9%,99.99%,100%,Total Request Count,Total Failure Count,Total Median Response Time,Total Average Response Time,Total Min Response Time,Total Max Response Time,Total Average Content Size
110,1789135756,12,POST,attacker,6.1,0.0,2200.0,2300.0,2300.0,2400.0,...,2600.0,2600.0,2600.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
111,1789135756,12,POST,legitimate,7.7,0.0,1500.0,1600.0,1600.0,1600.0,...,1800.0,1800.0,1800.0,263,0,1400,1261.670528,200.183667,1948.905035,870.000000
112,1789135756,12,NaN,Aggregated,13.8,0.0,1600.0,2100.0,2200.0,2300.0,...,2600.0,2600.0,2600.0,450,0,1600,1608.450184,200.183667,2693.519002,1096.004444
113,1789135757,4,POST,attacker,6.1,0.0,2300.0,2300.0,2400.0,2400.0,...,2600.0,2600.0,2600.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
114,1789135757,4,POST,legitimate,7.7,0.0,1500.0,1600.0,1600.0,1600.0,...,1800.0,1800.0,1800.0,266,0,1400,1249.936148,200.183667,1948.905035,870.000000
115,1789135757,4,NaN,Aggregated,13.8,0.0,1600.0,2100.0,2200.0,2300.0,...,2600.0,2600.0,2600.0,453,0,1600,1599.263244,200.183667,2693.519002,1094.507726
116,1789135758,4,POST,attacker,5.8,0.0,2300.0,2300.0,2400.0,2400.0,...,2600.0,2600.0,2600.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
117,1789135758,4,POST,legitimate,7.4,0.0,1500.0,1600.0,1600.0,1600.0,...,1800.0,1800.0,1800.0,269,0,1400,1238.455772,200.183667,1948.905035,870.000000
118,1789135758,4,NaN,Aggregated,13.2,0.0,1600.0,2100.0,2200.0,2300.0,...,2600.0,2600.0,2600.0,456,0,1600,1590.192624,200.183667,2693.519002,1093.030702
119,1789135759,4,POST,attacker,5.5,0.0,2300.0,2400.0,2400.0,2400.0,...,2600.0,2600.0,2600.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
120,1789135759,4,POST,legitimate,7.2,0.0,1500.0,1600.0,1600.0,1600.0,...,1800.0,1800.0,1800.0,273,0,1400,1223.551424,200.183667,1948.905035,870.000000
121,1789135759,4,NaN,Aggregated,12.7,0.0,1600.0,2100.0,2300.0,2300.0,...,2600.0,2600.0,2600.0,460,0,1600,1578.288636,200.183667,2693.519002,1091.091304
122,1789135760,4,POST,attacker,4.8,0.0,2300.0,2300.0,2400.0,2400.0,...,2600.0,2600.0,2600.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
123,1789135760,4,POST,legitimate,6.6,0.0,1400.0,1600.0,1600.0,1600.0,...,1700.0,1700.0,1700.0,276,0,1400,1212.650149,200.183667,1948.905035,870.000000
124,1789135760,4,NaN,Aggregated,11.4,0.0,1600.0,1700.0,2200.0,2300.0,...,2600.0,2600.0,2600.0,463,0,1600,1569.491739,200.183667,2693.519002,1089.658747
125,1789135761,4,POST,attacker,4.1,0.0,2300.0,2300.0,2400.0,2400.0,...,2600.0,2600.0,2600.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
126,1789135761,4,POST,legitimate,6.3,0.0,1100.0,1500.0,1600.0,1600.0,...,1700.0,1700.0,1700.0,280,0,1400,1198.506296,200.183667,1948.905035,870.000000
127,1789135761,4,NaN,Aggregated,10.4,0.0,1500.0,1700.0,2100.0,2200.0,...,2600.0,2600.0,2600.0,467,0,1600,1557.955026,200.183667,2693.519002,1087.777302
128,1789135762,4,POST,attacker,4.1,0.0,2200.0,2300.0,2300.0,2300.0,...,2500.0,2500.0,2500.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
129,1789135762,4,POST,legitimate,6.3,0.0,250.0,1300.0,1500.0,1500.0,...,1700.0,1700.0,1700.0,282,0,1400,1191.522076,200.183667,1948.905035,870.000000
130,1789135762,4,NaN,Aggregated,10.4,0.0,1300.0,1600.0,1900.0,2100.0,...,2500.0,2500.0,2500.0,469,0,1600,1552.222728,200.183667,2693.519002,1086.848614
131,1789135763,4,POST,attacker,3.5,0.0,2100.0,2200.0,2300.0,2300.0,...,2400.0,2400.0,2400.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
132,1789135763,4,POST,legitimate,5.8,0.0,230.0,240.0,640.0,1300.0,...,1600.0,1600.0,1600.0,286,0,1400,1178.031057,200.183667,1948.905035,870.000000
133,1789135763,4,NaN,Aggregated,9.3,0.0,250.0,1400.0,1600.0,2100.0,...,2400.0,2400.0,2400.0,473,0,1600,1541.015045,200.183667,2693.519002,1085.014799
134,1789135764,4,POST,attacker,2.9,0.0,2100.0,2100.0,2100.0,2100.0,...,2100.0,2100.0,2100.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
135,1789135764,4,POST,legitimate,5.5,0.0,230.0,240.0,240.0,240.0,...,1600.0,1600.0,1600.0,289,0,1400,1168.151036,200.183667,1948.905035,870.000000
136,1789135764,4,NaN,Aggregated,8.4,0.0,230.0,240.0,640.0,1000.0,...,2100.0,2100.0,2100.0,476,0,1600,1532.728747,200.183667,2693.519002,1083.659664
137,1789135765,4,POST,attacker,1.8,0.0,1400.0,1400.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,187,0,2100,2096.167027,894.661942,2693.519002,1413.860963
138,1789135765,4,POST,legitimate,4.8,0.0,220.0,230.0,230.0,240.0,...,250.0,250.0,250.0,292,0,1400,1158.508394,200.183667,1948.905035,870.000000
139,1789135765,4,NaN,Aggregated,6.6,0.0,230.0,230.0,240.0,240.0,...,1900.0,1900.0,1900.0,479,0,1600,1524.567192,200.183667,2693.519002,1082.321503

In [23]:
%%writefile /content/locustfile.py
# low-and-slow
from locust import HttpUser, task, between, LoadTestShape

MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

SMALL_PROMPT = "Explain AI inference briefly."

MEDIUM_PROMPT = (
    "Explain how an AI inference server handles requests, batching, "
    "token generation, and resource usage. "
) * 10

EXPENSIVE_PROMPT = (
    "Explain in detail the architecture of an AI inference server, "
    "including request scheduling, KV cache, GPU execution, batching, "
    "prefill, decode, memory usage, and latency. "
) * 30


class LegitimateUser(HttpUser):
    wait_time = between(0.5, 1.5)
    weight = 1

    @task
    def legitimate_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": SMALL_PROMPT
                    }
                ],
                "max_tokens": 32,
                "temperature": 0
            },
            name="legitimate"
        )


class AttackerUser(HttpUser):
    wait_time = between(1.5, 2.5)

    @task
    def attack_request(self):
        self.client.post(
            "/v1/chat/completions",
            json={
                "model": MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": EXPENSIVE_PROMPT
                    }
                ],
                "max_tokens": 256,
                "temperature": 0
            },
            name="attacker"
        )


class LowSlowShape(LoadTestShape):

    def tick(self):
        run_time = self.get_run_time()

        # 0-10s: normal traffic only
        if run_time < 10:
            return (
                4,
                4,
                [LegitimateUser]
            )

        # 10-40s: low-rate expensive attackers appear
        if run_time < 40:
            return (
                8,
                2,
                [LegitimateUser, AttackerUser]
            )

        # 40-50s: attacker disappears
        if run_time < 50:
            return (
                4,
                4,
                [LegitimateUser]
            )

        return None

Overwriting /content/locustfile.py

In [24]:
!locust \
  -f /content/locustfile.py \
  --headless \
  --host http://127.0.0.1:8000 \
  --csv /content/results/low_slow \
  --csv-full-history

[2026-09-11 14:09:27,091] 626a8ef1d973/INFO/locust.main: Starting Locust 2.46.5
[2026-09-11 14:09:27,092] 626a8ef1d973/INFO/locust.runners: Shape test starting.
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2026-09-11 14:09:27,093] 626a8ef1d973/INFO/locust.runners: Shape worker starting
[2026-09-11 14:09:27,093] 626a8ef1d973/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 14:09:27,093] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 14:09:27,094] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate       8     0(0.00%) |    221     211     231    220 |    0.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated       8     0(0.00%) |    221     211     231    220 |    0.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      13     0(0.00%) |    220     205     231    220 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      13     0(0.00%) |    220     205     231    220 |    4.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      20     0(0.00%) |    221     205     237    220 |    3.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      20     0(0.00%) |    221     205     237    220 |    3.00        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      28     0(0.00%) |    223     205     237    220 |    3.33        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      28     0(0.00%) |    223     205     237    220 |    3.33        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     legitimate      33     0(0.00%) |    224     205     240    230 |    3.29        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      33     0(0.00%) |    224     205     240    230 |    3.29        0.00

[2026-09-11 14:09:37,104] 626a8ef1d973/INFO/locust.runners: Shape test updating to 8 users at 2.00 spawn rate
[2026-09-11 14:09:37,105] 626a8ef1d973/INFO/locust.runners: Ramping to 8 users at a rate of 2.00 per second
[2026-09-11 14:09:38,106] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 2, "LegitimateUser": 6} (8 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       1     0(0.00%) |   1850    1850    1850   1850 |    0.00        0.00
POST     legitimate      42     0(0.00%) |    230     205     274    230 |    3.33        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      43     0(0.00%) |    267     205    1850    230 |    3.33        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       2     0(0.00%) |   1849    1849    1850   1849 |    0.00        0.00
POST     legitimate      54     0(0.00%) |    230     205     274    230 |    3.30        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      56     0(0.00%) |    288     205    1850    230 |    3.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       2     0(0.00%) |   1849    1849    1850   1849 |    0.20        0.00
POST     legitimate      62     0(0.00%) |    233     205     274    230 |    4.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      64     0(0.00%) |    283     205    1850    230 |    4.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       4     0(0.00%) |   1868    1849    1888   1888 |    0.20        0.00
POST     legitimate      73     0(0.00%) |    233     205     274    230 |    4.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      77     0(0.00%) |    318     205    1888    230 |    4.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       6     0(0.00%) |   1871    1849    1891   1891 |    0.40        0.00
POST     legitimate      81     0(0.00%) |    235     205     274    230 |    4.40        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      87     0(0.00%) |    348     205    1891    230 |    4.80        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       6     0(0.00%) |   1871    1849    1891   1891 |    0.40        0.00
POST     legitimate      90     0(0.00%) |    235     205     274    230 |    4.70        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated      96     0(0.00%) |    337     205    1891    230 |    5.10        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       8     0(0.00%) |   1869    1849    1891   1891 |    0.50        0.00
POST     legitimate     101     0(0.00%) |    236     205     274    230 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     109     0(0.00%) |    356     205    1891    240 |    5.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       8     0(0.00%) |   1869    1849    1891   1891 |    0.40        0.00
POST     legitimate     112     0(0.00%) |    236     205     274    230 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     120     0(0.00%) |    345     205    1891    240 |    5.20        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker       9     0(0.00%) |   1868    1849    1891   1891 |    0.60        0.00
POST     legitimate     122     0(0.00%) |    237     205     274    240 |    5.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     131     0(0.00%) |    349     205    1891    240 |    5.70        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      10     0(0.00%) |   1867    1849    1891   1891 |    0.40        0.00
POST     legitimate     133     0(0.00%) |    237     205     274    240 |    4.90        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     143     0(0.00%) |    351     205    1891    240 |    5.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      11     0(0.00%) |   1862    1820    1891   1891 |    0.60        0.00
POST     legitimate     141     0(0.00%) |    237     205     274    240 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     152     0(0.00%) |    355     205    1891    240 |    5.40        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      12     0(0.00%) |   1859    1820    1891   1891 |    0.50        0.00
POST     legitimate     151     0(0.00%) |    238     205     274    240 |    5.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     163     0(0.00%) |    358     205    1891    240 |    5.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1861    1820    1891   1891 |    0.60        0.00
POST     legitimate     160     0(0.00%) |    239     205     280    240 |    4.90        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     174     0(0.00%) |    369     205    1891    240 |    5.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      14     0(0.00%) |   1861    1820    1891   1891 |    0.50        0.00
POST     legitimate     170     0(0.00%) |    238     204     280    240 |    5.10        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     184     0(0.00%) |    362     204    1891    240 |    5.60        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.50        0.00
POST     legitimate     181     0(0.00%) |    238     204     280    240 |    4.90        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     197     0(0.00%) |    370     204    1891    240 |    5.40        0.00

[2026-09-11 14:10:07,143] 626a8ef1d973/INFO/locust.runners: Shape test updating to 4 users at 4.00 spawn rate
[2026-09-11 14:10:07,143] 626a8ef1d973/INFO/locust.runners: Ramping to 4 users at a rate of 4.00 per second
[2026-09-11 14:10:07,144] 626a8ef1d973/INFO/locust.runners: All users spawned: {"AttackerUser": 0, "LegitimateUser": 4} (4 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.50        0.00
POST     legitimate     188     0(0.00%) |    237     204     280    240 |    5.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     204     0(0.00%) |    365     204    1891    240 |    5.50        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.50        0.00
POST     legitimate     193     0(0.00%) |    237     204     280    240 |    4.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     209     0(0.00%) |    361     204    1891    240 |    5.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.40        0.00
POST     legitimate     199     0(0.00%) |    237     204     280    240 |    4.50        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     215     0(0.00%) |    357     204    1891    240 |    4.90        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.30        0.00
POST     legitimate     207     0(0.00%) |    236     204     280    240 |    4.00        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     223     0(0.00%) |    352     204    1891    240 |    4.30        0.00

Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.20        0.00
POST     legitimate     213     0(0.00%) |    235     204     280    240 |    3.80        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     229     0(0.00%) |    349     204    1891    240 |    4.00        0.00

[2026-09-11 14:10:17,155] 626a8ef1d973/INFO/locust.runners: Shape test stopping
[2026-09-11 14:10:17,176] 626a8ef1d973/INFO/locust.main: Shape test completed, shutting down
[2026-09-11 14:10:17,177] 626a8ef1d973/INFO/locust.main: Shutting down (exit code 0)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
POST     attacker      16     0(0.00%) |   1859    1820    1891   1891 |    0.32        0.00
POST     legitimate     213     0(0.00%) |    235     204     280    240 |    4.29        0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated     229     0(0.00%) |    349     204    1891    240 |    4.61        0.00

Response time percentiles (approximated)
Type     Name      50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------||--------|------|------|------|------|------|------|------|------|------|------|------
POST     attacker     1900   1900   1900   1900   1900   1900   1900   1900   1900   1900   1900     16
POST     legitimate      240    240    250    250    260    260    260    270    280    280    280    213
--------||--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated      240    250    250    260    260   1900   1900   1900   1900   1900   1900    229

In [25]:
import pandas as pd

df = pd.read_csv("/content/results/low_slow_stats.csv")
display(df)

hist = pd.read_csv("/content/results/low_slow_stats_history.csv")
display(hist.tail(30))

,Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,...,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
0,POST,attacker,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000,0.322025,...,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900
1,POST,legitimate,213,0,240.000000,235.768356,204.112324,280.653782,870.000000,4.286959,...,240,250,250,260,260,260,270,280,280,280
2,NaN,Aggregated,229,0,240.000000,349.215727,204.112324,1891.112628,956.917031,4.608984,...,250,250,260,260,1900,1900,1900,1900,1900,1900

,Timestamp,User Count,Type,Name,Requests/s,Failures/s,50%,66%,75%,80%,...,99.9%,99.99%,100%,Total Request Count,Total Failure Count,Total Median Response Time,Total Average Response Time,Total Min Response Time,Total Max Response Time,Total Average Content Size
110,1789135808,4,POST,attacker,0.5,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
111,1789135808,4,POST,legitimate,5.0,0.0,240.0,250.0,250.0,260.0,...,280.0,280.0,280.0,185,0,240.000000,238.332297,204.295126,280.653782,870.000000
112,1789135808,4,NaN,Aggregated,5.5,0.0,240.0,250.0,260.0,260.0,...,1900.0,1900.0,1900.0,201,0,240.000000,367.379187,204.295126,1891.112628,969.024876
113,1789135809,4,POST,attacker,0.5,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
114,1789135809,4,POST,legitimate,5.0,0.0,240.0,250.0,250.0,250.0,...,280.0,280.0,280.0,188,0,240.000000,237.919078,204.295126,280.653782,870.000000
115,1789135809,4,NaN,Aggregated,5.5,0.0,240.0,250.0,260.0,260.0,...,1900.0,1900.0,1900.0,204,0,240.000000,365.100629,204.295126,1891.112628,967.568627
116,1789135810,4,POST,attacker,0.5,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
117,1789135810,4,POST,legitimate,4.8,0.0,240.0,240.0,250.0,250.0,...,280.0,280.0,280.0,191,0,240.000000,237.704557,204.295126,280.653782,870.000000
118,1789135810,4,NaN,Aggregated,5.3,0.0,240.0,250.0,250.0,260.0,...,1900.0,1900.0,1900.0,207,0,240.000000,363.059479,204.295126,1891.112628,966.154589
119,1789135811,4,POST,attacker,0.5,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
120,1789135811,4,POST,legitimate,4.8,0.0,230.0,240.0,240.0,250.0,...,260.0,260.0,260.0,193,0,240.000000,237.433227,204.295126,280.653782,870.000000
121,1789135811,4,NaN,Aggregated,5.3,0.0,230.0,240.0,250.0,250.0,...,1900.0,1900.0,1900.0,209,0,240.000000,361.609352,204.295126,1891.112628,965.234450
122,1789135812,4,POST,attacker,0.4,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
123,1789135812,4,POST,legitimate,4.5,0.0,220.0,240.0,240.0,240.0,...,260.0,260.0,260.0,198,0,240.000000,237.097134,204.295126,280.653782,870.000000
124,1789135812,4,NaN,Aggregated,4.9,0.0,230.0,240.0,240.0,250.0,...,1900.0,1900.0,1900.0,214,0,240.000000,358.397076,204.295126,1891.112628,963.009346
125,1789135813,4,POST,attacker,0.4,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
126,1789135813,4,POST,legitimate,4.2,0.0,230.0,240.0,240.0,250.0,...,260.0,260.0,260.0,200,0,240.000000,236.990998,204.295126,280.653782,870.000000
127,1789135813,4,NaN,Aggregated,4.6,0.0,230.0,240.0,240.0,250.0,...,1900.0,1900.0,1900.0,216,0,240.000000,357.175654,204.295126,1891.112628,962.148148
128,1789135814,4,POST,attacker,0.3,0.0,1900.0,1900.0,1900.0,1900.0,...,1900.0,1900.0,1900.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
129,1789135814,4,POST,legitimate,4.0,0.0,220.0,230.0,240.0,240.0,...,250.0,250.0,250.0,204,0,240.000000,236.688409,204.295126,280.653782,870.000000
130,1789135814,4,NaN,Aggregated,4.3,0.0,220.0,230.0,240.0,240.0,...,1900.0,1900.0,1900.0,220,0,240.000000,354.709896,204.295126,1891.112628,960.472727
131,1789135815,4,POST,attacker,0.3,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
132,1789135815,4,POST,legitimate,4.0,0.0,220.0,220.0,230.0,230.0,...,240.0,240.0,240.0,207,0,240.000000,236.415965,204.295126,280.653782,870.000000
133,1789135815,4,NaN,Aggregated,4.3,0.0,220.0,220.0,230.0,230.0,...,1800.0,1800.0,1800.0,223,0,240.000000,352.869266,204.295126,1891.112628,959.255605
134,1789135816,4,POST,attacker,0.2,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
135,1789135816,4,POST,legitimate,3.9,0.0,220.0,220.0,220.0,230.0,...,240.0,240.0,240.0,209,0,240.000000,236.237689,204.295126,280.653782,870.000000
136,1789135816,4,NaN,Aggregated,4.1,0.0,220.0,220.0,220.0,230.0,...,240.0,240.0,240.0,225,0,240.000000,351.668527,204.295126,1891.112628,958.462222
137,1789135817,4,POST,attacker,0.2,0.0,1800.0,1800.0,1800.0,1800.0,...,1800.0,1800.0,1800.0,16,0,1891.112628,1859.483856,1820.355737,1891.112628,2114.000000
138,1789135817,4,POST,legitimate,3.8,0.0,220.0,220.0,220.0,230.0,...,240.0,240.0,240.0,213,0,240.000000,235.768356,204.112324,280.653782,870.000000
139,1789135817,4,NaN,Aggregated,4.0,0.0,220.0,220.0,220.0,230.0,...,240.0,240.0,240.0,229,0,240.000000,349.215727,204.112324,1891.112628,956.917031